---
# We need the systemd for the kubeadm and it's default from 16.04+
dist: xenial
language: minimal

stages:
  - name: lint
    if: type IN (push, pull_request)
  - name: deploy
    if: type IN (push, pull_request)
  - name: publish
    if: type = push AND branch = master

jobs:
  include:
    - stage: lint
      env:
        - REPO_DIR=/home/travis/build/NBISweden/LocalEGA-helm
      install:
        # Installing Helm
        - curl https://raw.githubusercontent.com/kubernetes/helm/v2.12.2/scripts/get > get_helm.sh && chmod 700 get_helm.sh && ./get_helm.sh
        - helm init --client-only
      script:
        # Check ega-charts format
        - >
          for dir in `ls ${REPO_DIR}/ega-charts`; do
            helm lint ${REPO_DIR}/ega-charts/$dir
            if [ $? != 0 ]; then
              travis_terminate 1
            fi
          done

    - stage: deploy
      sudo: required
      before_script:
        # Decrypt config
        - >
          openssl aes-256-cbc
          -K $encrypted_key
          -iv $encrypted_iv
          -in .ssh-keys/staging.enc
          -out .ssh-keys/kube-config
          -d
        # Decrypt key
        - >
          openssl aes-256-cbc
          -K $encrypted_key
          -iv $encrypted_iv
          -in .ssh-keys/travis.enc
          -out .ssh-keys/travis
          -d
        - chmod 600 .ssh-keys/travis
        # set up ssh tunnel
        - ssh-keyscan $STAGING >> ~/.ssh/known_hosts
        - ssh -N -f -L localhost:9630:localhost:6443 ubuntu@$STAGING -i .ssh-keys/travis
        # Download kubectl
        - curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v1.13.0/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
        # Download helm
        - curl https://raw.githubusercontent.com/kubernetes/helm/v2.12.2/scripts/get > get_helm.sh && chmod 700 get_helm.sh && ./get_helm.sh
        # create config files
        - echo -e "127.0.0.1\tkubernetes" | sudo tee -a /etc/hosts
        - export KUBECONFIG=.ssh-keys/kube-config
        - mkdir -p ega-charts/localega/config
        - echo "JSUgLSotIG1vZGU6IGVybGFuZyAtKi0KJSUKW3tyYWJiaXQsW3tsb29wYmFja191c2VycywgWyBdIH0sIHt0Y3BfbGlzdGVuZXJzLCBbIDU2NzIgXSB9LCB7c3NsX2xpc3RlbmVycywgWyBdIH0sCiAgICAgICAge2hpcGVfY29tcGlsZSwgZmFsc2UgfSwge2RlZmF1bHRfdmhvc3QsICIvIn0sIHtkZWZhdWx0X3VzZXIsICAiZ3Vlc3QifSwKICAgICAgICB7ZGVmYXVsdF9wYXNzLCAgImd1ZXN0In0sIHtkZWZhdWx0X3Blcm1pc3Npb25zLCBbIi4qIiwgIi4qIiwiLioiXX0sCiAgICAgICAge2RlZmF1bHRfdXNlcl90YWdzLCBbYWRtaW5pc3RyYXRvcl19LCB7ZGlza19mcmVlX2xpbWl0LCAiMUdCIn1dfSwKICAgICAgICB7cmFiYml0bXFfbWFuYWdlbWVudCwgWyB7IGxpc3RlbmVyLCBbIHsgcG9ydCwgMTU2NzIgfSwgeyBzc2wsIGZhbHNlIH1dIH0sCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIHsgbG9hZF9kZWZpbml0aW9ucywgIi9ldGMvcmFiYml0bXEvZGVmcy5qc29uIn0gXX0KXS4=" | base64 -d > ega-charts/localega/config/rabbitmq.config
        - echo "eyJyYWJiaXRfdmVyc2lvbiI6IjMuNi4xNiIsCiAgICAgInVzZXJzIjpbeyJuYW1lIjoiZ3Vlc3QiLCJwYXNzd29yZF9oYXNoIjoiSnpUdUp2SzA3VmlNMkhpODlETFMyTEw2dUVWVGNIdGtVQmszV0VDR2w2YmxpSERwIiwiaGFzaGluZ19hbGdvcml0aG0iOiJyYWJiaXRfcGFzc3dvcmRfaGFzaGluZ19zaGEyNTYiLCJ0YWdzIjoiYWRtaW5pc3RyYXRvciJ9XSwKCiAgICAgInZob3N0cyI6W3sibmFtZSI6Ii8ifV0sCiAgICAgInBlcm1pc3Npb25zIjpbeyJ1c2VyIjoiZ3Vlc3QiLCJ2aG9zdCI6Ii8iLCJjb25maWd1cmUiOiIuKiIsIndyaXRlIjoiLioiLCJyZWFkIjoiLioifV0sCiAicGFyYW1ldGVycyI6W10sCiAgICAgImdsb2JhbF9wYXJhbWV0ZXJzIjpbeyJuYW1lIjoiY2x1c3Rlcl9uYW1lIiwidmFsdWUiOiJyYWJiaXRAbG9jYWxob3N0In1dLAogInBvbGljaWVzIjpbXSwKICAgICAicXVldWVzIjpbeyJuYW1lIjoiZmlsZXMiLCJ2aG9zdCI6Ii8iLCJkdXJhYmxlIjp0cnVlLCJhdXRvX2RlbGV0ZSI6ZmFsc2UsImFyZ3VtZW50cyI6e319LAogeyJuYW1lIjoiYXJjaGl2ZWQiLCJ2aG9zdCI6Ii8iLCJkdXJhYmxlIjp0cnVlLCJhdXRvX2RlbGV0ZSI6ZmFsc2UsImFyZ3VtZW50cyI6e319LAogeyJuYW1lIjoic3RhYmxlSURzIiwidmhvc3QiOiIvIiwiZHVyYWJsZSI6dHJ1ZSwiYXV0b19kZWxldGUiOmZhbHNlLCJhcmd1bWVudHMiOnt9fV0sCiJleGNoYW5nZXMiOlt7Im5hbWUiOiJsZWdhIiwidmhvc3QiOiIvIiwidHlwZSI6InRvcGljIiwiZHVyYWJsZSI6dHJ1ZSwiYXV0b19kZWxldGUiOmZhbHNlLCJpbnRlcm5hbCI6ZmFsc2UsImFyZ3VtZW50cyI6e319LAogICAgICAgICAgICAgIHsibmFtZSI6ImNlZ2EiLCJ2aG9zdCI6Ii8iLCJ0eXBlIjoidG9waWMiLCJkdXJhYmxlIjp0cnVlLCJhdXRvX2RlbGV0ZSI6ZmFsc2UsImludGVybmFsIjpmYWxzZSwiYXJndW1lbnRzIjp7fX1dLAogImJpbmRpbmdzIjpbeyJzb3VyY2UiOiJsZWdhIiwgInZob3N0IjoiLyIsICJkZXN0aW5hdGlvbiI6ImFyY2hpdmVkIiwgICJkZXN0aW5hdGlvbl90eXBlIjoicXVldWUiLCAicm91dGluZ19rZXkiOiJhcmNoaXZlZCIsICJhcmd1bWVudHMiOnt9fV0KfQ==" | base64 -d > ega-charts/localega/config/defs.json
        - echo "LS0tLS1CRUdJTiBQR1AgUFJJVkFURSBLRVkgQkxPQ0stLS0tLQpWZXJzaW9uOiBQR1B5IHYwLjQuMwoKeGNhR0JGd2FJMUFCRUFDbmhjRU9OL3pzbm1wUFlwUG04Yk5mb25sbXVWWFF5R3dZUzlLdVBUVHFVUHdyVGVFVgpxR2xGM3VlbWhLL251ZTIyNDc2L3pqaW0wbngzMGxHclBjZ0ljQnNrY2p6V2R3WnpwajAxMGZkeFJMY0tJQllWCmpMc0gwcXpMYkJNbTFPdFBHU0tJK3JCK3lsNzJpRkl0d1BiWjVSQ3Fmejh0VkFMWXphVVhwMVQ5VDcyakViSWYKOWxJdzU2SkFPKy9Ld2QyS0pRV0tPU1RXMUl1VGlCVFh3UnNSN3JjSDlubFNXT0gzMEwwYnhWWkJmaS9OdkpEWAp3Z29rb0tCellLNkxFSkMva3pnTml2TEJmMEJaUFlVVjQzYlJYYmhOb3E4OEZhL3NPMzY0T3MwbkNkS3c0OHB0CnFZMEVXSG01eXpaSDgyenNWalFhQmpFNGRkTWY5NDJKZUZWQ0p4WTRiYmVPRHNwS3FOT21ySGZ4d25qV1BGMUcKWXdCdkVkL2lrZDJ4WEhrbnRkSTRNYkJBN2dhbXdqYlQyekNkdVFPenBjWElnckVVaVU4M1dES0QwZHNDKzE4dAppb0cxY2FFeUh1eXV2c1ZnSEdEOVUxUWtCU3Z5RXdvSHhFaE0vWmNCMFdueUtDbm9SL1VIMDNtZjhGTVQ1Zi91CkFLTUdhZTRyN0d1WENoOXlvN3g1L3l0VUN5TWlKK2trUExYekJnTjkySUJQUlB6SHBpcS9WRy9SRmp0MVJReXEKSFp2VHNmbFNZNEhwLzVyOTJBSVRCbVVUcUg5UUd6aWEwRDZaNlMwYnB0SytmU29KQktsTEU2TG1zVmc5MVBDUwpuRXp5UVJSZkYyYXBLVTEwM0R1V0U1dzRaTmlaTGFSL2FDYnBKRnFsWnpSdmthamU5ZU5KZktMRE53QVJBUUFCCi9na0RDQTU4ckJNZ1BiY2k3Nks5b2pLWG9QSlZDWE9vQlc0ejNnbjBYTzBGSGNpazhQLzdJRCtOU2RGUXY2ZEQKUmMrNUZxWHFleURWTHRVMVBvL0pBOHdDdUtZcDlMVVgwcHcrVzNlZ0FCNXdWN09MME5zR1JaelNBTjQ2cFYxcApTOExLNzk0d3JmdzRwZXN4WjAyMU5ORHIxT3NNRlluMlBjWjl0R295R3dJeS9wREU1VWZIRGJta2RnbmNwN05XCk5MQ3dRTXpKdTc4SExRZEVmN0ZvWHgyTU4vdm13Vkt3WTNQbnh6cTI4akZzblgrY3Q5ak1nNmlVdU95YmlGQlcKNjJhbWFFNE9oZDdHQWx0b0NWZkZKLzBlemxTOVRCdm9wdmtGTVhCWFdHNHRmTEVhek94YklwSmUxZ2pkbWo0ZApnYXA1MUViUWVENWFNK0picnowdWNVUXQyRzhVYW5hVUFockhUcy80akRKTmRUdlZ1QUVEOE55eTNkbkhXNTZoCjBybzlpcFlvb09DM2cvL0RSNUg1djR1KzlOa3BiY2w3VUpCcWtuaFhvYklwVm12QW1tY2V6U3Z2RU9JOU5HY2sKbGo1YVBSbVdoRjNUWmxKTXBBS0MxNXBpUWhjeTYxQ08zWVhubVFxQ2tvOUFsbDUrK3QyUWNMZFZZQ2JReGc2SApTdVY2a2w0b2VCT3F6alREZHl3MVNDOG9mNG9yQkc0RjExR2oxV2xuUkl6MjNCVXY0TTNFdnl6OVBZa1BRRkovCmoyZlpLZE52TlBRWmZCekR5VGltdlRPZWFGSTFCb1NiYkZEc2l3ZVVid3plTTNzL2FjMmpSTC9KY29qN2RmRVEKb2JlNitmWkgvcGl4UDFOcnRRMENUM1VBZUZrcTJHN2ZFdUJDTTJjOXhqaHplREVLaWZUemRmN1M3ekZnWU5oeQprNDVENmwrZTBXeUJnUG9qWC9sQVkvODZtbk1jTVRLWFhIcTdPaS9OdlBSK1Q0em5GZXJqWGxhcHp2SE8yd2hyCnhWRVZic3Q4VnZaeGRqUnYyUHJtUU9yRldZRFUydnl6dlVSaG1tQUJqT3puTlZUQ09wZURiSXNLZkRBZUdiaGkKaVJ6V3FheDlaeUFDS3NpbGlMb2NGR2JGWVdEYTFKQk00S1BhdmtpRXc5U0ZHY01iTjRQemloQ0dNOUx5R0VZdQpEMUFZRys2akYvTlJzRm5pbmExUHZEbWtNY242R0dWZHdiK3dkZDYycGNJMnowMVI3cnlVQW5xTXB5a2N0RVhYCndNc1dOUWlPaHd4Z3hJQVpVdmhtT09QbnhZQmtWQXc5MnhNbjVpZjRSbTIwY0R4THZodnRuL25Wbk5WM2tLVVoKYm9yMzNxdFd3K3RpQ1d5cXZZQnl3M1JDeGRvZzBoL2NVTXBSQ25jSEVwczdra1Y3TFNRSmVpRmhYZmpZK2hlMQpPYlRGMXJDRTN4ZzlMcUV4MzFodEFsUlNGSkt2VkFmYXJ2UEMyTHV6UFU5ZzJSUExxOWkxZ1NpckxiWTQyaG9NCk1pQyt6RkhLQ3lONjVvVFZhcnpEYXdYRkxSVGI3dUtwVUwrSkdabUZha1ZWL281aWZpalZnd1YwVjJjSHZ4clkKdTFHVitQdFgrNjY5MzlCeVFHUEpNL2RyeTlyUjhzeGZkeW8xK3M2VVBVc2crVVNEUGNnb1crb2Z3NDFUT2NwRgpSSGVoUFBkNzVtb3BuR1hkTnRFV0JYNUlINnZNb1NRN3d1b09lR3BOam5Jb0haSlRVSWQ0Q1RuSzdvSzhQc2o1CmF6YytyTHdKY1JLM1daR1d2ZDlwbUQxVTdUSW1XY3hFMiszUlZ4ZWgvVzRBS3JKQlNBWWRsZHlOWEM1V3J2aTIKd2YwOE1LYlozb2tmdzFrWnFVNEFGOUhzVjJINmUxZmc0UTEvVllYeXUxUE15Q2swTVNJYWkxclo1ejZnM3NiNAptdlhPOWtvaWpFakNsSCtQRmFoUXhiTmw2ZS9xRDFEZDJkREZjbk5JenJjZW4zTk5GVGRoZmpSZk1reS9hQXFPClA3MmhROFZGR0pFWTVEbytkTDdvM0cva0tUb0NTYnZnUS9hVzAxbXh6aklNRU9CaHRiQ21pMHllbjBVclpudXkKSXZpc0VUQ0tTNXBJTzgzRWtpejJiLzhJbitHb1BxOHUxdDZ5RjR4NTI2Q0tlWkUwcnJvUndTQ0ZZcGkyRk1uZAppMTh4RWFUWk5WQlFEajRFM092bUFWSWJOOCs0WFBqZURoVWZ4aStkeTQ3enEyNERaREI4WTJsOWk2RlNwYnZjClovNDBFcXJ0RE9wUTZ5c205QncyMHJkaENvZ0NGQW0vMGlJeDFOWUJwdDhSaVQ4UVRwTzVjUUxOTjFSbGMzUWcKVUVkUUlDaEhaVzVsY21GMFpXUWdabTl5SUhWelpTQnBiaUJNYjJOaGJFVkhRUzRwSUR4MFpYTjBRR056WXk1bQphVDdDd1hNRUV3RUlBQjBGQWx3YUkxQUNHdzRFQ3drSUJ3VVZDQWtLQ3dVV0FnTUJBQUllQVFBS0NSREd5WXlWCkg3U2NoMWg0RC80NGRFL0tlZXZrQU9HUGZoTWtNa1VvQlo2bG9YSlVnZ1hHa3pId1VWcVhGMGFEaEduVWJNMHgKOHBUOERNNXVMc0ZyLzRxOHdpOVNGdUtFMjg4RGtlSGlzYlJCdUVpMlJKcnRWbFRmNWJYcGY1UWprd1dSYmgwUgpEU1hOaEF4clB2TEhCaWdyUWZZWmxPWDVNQnlLYU5zVkZMQzdVN3JpNUo5QTMzaXpiYUtvQ1ozNU14UHpSQ1hVCktGR0NnK3o1UHJHT1drZDl1VW9qd1BMaHJrT0FJMStNZXgxYlhTald2bTdoaFAzWmI3UkVpNkVyS1BLNXM5amwKZVhiMWNwb0RsamI1VHJ3SHhVa0VpTVJGOWlOK3hPaVFDUzZJNXYzbVIwRG5CTTR6WkVWL1lWREc2bWVWWFNWdwpzYlQ4UDd5QUxOOTVDQjllZndiWTdkd0ZxTkFyQklGaFc3UHkzRFJRVkZpb2tkZ2k1UkJ2a01mc2d3TXhTUXpSCmtIakxYd0JZbmhXYTJWSDBWQXllYlVtSDhiR2k4SVJkbjJKL1BFRjZJLzhyT0p6bThrVzdyL3NiR0ZmUmFHVVIKU0JCeXRmZEY5MWF5a2FqVE0yYXVNNjgrU3ZWVVVBcUQyZHdxUWQ5VG1mZlQwbHhrQ0NnTng3UGVJS0tjYjdMbApkWDVvczBPN3JGOENzRkFwWHI5cHpPeFNzTjhBWTNIU1IwUVdDTHJrOEtvRUxZbkVRZ0JpRXRHRVRjQlp5WmQxCnYvN01jdk1IelUyNTE4b1krRG9JREFpSFkyTTRqYVlidWxDNyt1NnB6dkp3V291QVhEcmhGOGhoVW1OdUM5emMKSCtWZVpDV3J0S1A2bmpBQ3lqbGpSYkQyajNiY2N1azlRWCs0MDBoODJGM1pMa0ZlRElRRnVRPT0KPWlKcjcKLS0tLS1FTkQgUEdQIFBSSVZBVEUgS0VZIEJMT0NLLS0tLS0K" | base64 -d > ega-charts/localega/config/key.1.sec
        - echo "LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb2dJQkFBS0NBUUVBdkpibm9USis1eDhHdjFBb3lSbllvbnF0amhRWFVMb0FJSWRHVzk1WUcxZEQ5VGNOClg0aUNub2EwQmlSUDNWL3ZTUjNzOU1rMThBM2t5c0xOQzQzSE44MHV4SmtXb1pYY0RzMi9UbCthZXV4eDZXVzQKL3pqdk9OYnE3eEFNdmtmTnc4MFltZ1lnS0p4VFNjQi9RYUhKSk5IYS9TWkxYKzM4UnFSU24xWTBtZWxiL0xUZAp2eVZMd0c4cGR0dllTUVlxckxPRWRXV0pJVkIwTmV5Z290UUxiTmFSMDhBbi9Mbm1EMDg5a1NMbFUrZDRWR0UwCnBNY0ZaQUREVDRaTSsxeXhDMTBucXc4NDBYeVQ1Mm44N0JSZktFdXVSR2IwQUdUbUVzckZwZGlMUGpSb0U4NXoKZHRjTlQ0WjRpTmNObkJYMXFEbjB6U3ZwcHZ2R3RmZnp1SzNmcXdJREFRQUJBb0lCQUVqOHptQ2d2bVNNcVh2WgpkaTkraFUwODFYYXJaK3FpVWZKRTZJSWRwMVBOamt1Vkp1UFdYVmNsSXY5TmhtdFMrYlQray9xWTlQc1hKWGtqCnMxL0pXMVRKWUZST08yZ0dLOGkrOEU5UXlPVFNKYlFDM25wSWVxMHc0SFB0YmtFbVlRaHFsQjdvU0FIdm5ueG8KdDllYTJkSWFOZnJMbTFoaExzWFlTdkhIMTB2SlR1cU9xU0NVaWlNY3JwYWJjMTlJaW9FbjdGTWQwKzZvWVpRQwpkM2FiMUxnSTdBdFRxODFmU1lidzZFM1RxNGpBRHY0UC8wOVNZSW9lek10NUZnVll3ZFNGUlpKaW5FZTFQMitsCmFBUWFJYmdFREZJUzkyWWt4V0lGYlJMdUVTWVFoTklyK0RVN044ZEVSc0ZQaU5qQVRrdUlsckQ2UXltVjh3bEUKazZMc3ZrRUNnWUVBMzNvWUlkMk9nS2VpbkJBckxlc1lyTHdwQkJXVXBCN1MrSWE3RHk1VkRvTENLRTh1S3Rncgp5MXlPUkJRdUc1ZzBnTnhDUVZsaE9HWVR6NHpaWkZDU01LWHlpeS9WNHRWQy9wYmVRdlg1QVFwM2RiSUZaUzVHCndZY0FBN2h2TkxkTFlpZTdLRFBNK1ZzT3oyY1plL0lWUFYwYVVaTC90NXhhaGdIbmpmZm40UE1DZ1lFQTJBa0oKSXVzdVNHQVJYcWhHT1hWczJSK00wLzZvcHpIc29CaWEzVGtJOGt3L2tibmRTcS90MW55MkZPbmhiNTVGbWQxMwpHLzhlR2VWWWVXam91YkNUbW90Z0YrY09aTEtjYkVtWDRjRExRRGdzbDZCNmFZdkpwZ2dtZmdTTnJCTUdkemcvCjYrNVlKY1k5b0J6ZmEyTnJyT2o5ZGRWRjN1cXZMTVIxaFVucDlHa0NnWUFiVVNaZ0JXQWs4OWpac05SR1lhVjcKZitpWG1qZTROQmhmenNCUTQ3Mzc3eG5pcVlNZ001cHUybHA5a2VYczg1Yi9aVzBuNWRBUGY5TE9IUTU1eDZ1SApETkh3RjZIU2YzVVgvOE1kZGtuQXlkRytia3RnaWQ2V1MzVkIveXFBekNNSDFZbDRLWlRWcWo3T05YRVZDSXQyCkc4cGF6Rmc3em4zMlFZZFhnRVUwNXdLQmdEUit0WmFqbVVLQy9aV0h4RkN3QlB3Wm00bmtCcTFpQjBLNzE5M0wKdnkzSmMyVUF5aEljLytrdnNyc1FQZlIyZkNrd1ZJSWNFdjl0NkhyUUVFVVc4RGNNaVJRbDFDeUo3bEt0NjFjegpGdkNLOWVMK1h1Q0kxRDRoR3VGaVQ5NnhYTS9aZmtiaFN0QWJCTnlFUjVIN3ZhMXRqREYyMnB5WllHbTdiMmN0CkY4bUpBb0dBVlc0ZldEOGtJUUMxN2lvT1U0WWRsRXZRMkMzR0d0RUlBMDN6cWRzYVVEZWNDcHR5M0NlQ01uOFkKRkJSMDI4bGd3RGlrVUxMVkJnbFdYQWJTMHVNSE9yanRLT2sydlQ0cExaMFNHU2RTVGltNk42K2hwVUNXMjRTUgpQcjJBaEJ5UnlHZmpLMTR0QVZaSUQxMlJQdHdtbW1uWjRBZHA2WDFlK3A2TVpkNDZrbTg9Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==" | base64 -d > ega-charts/localega/config/ssl.key
        - echo "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURvakNDQW9xZ0F3SUJBZ0lVVHFDWVpaVXVnQUQyeXZsL2x0cGtFWkVYY2hjd0RRWUpLb1pJaHZjTkFRRUwKQlFBd2ZqRUxNQWtHQTFVRUJoTUNSa2t4RURBT0JnTlZCQWdNQjBacGJteGhibVF4RGpBTUJnTlZCQWNNQlVWegpjRzl2TVF3d0NnWURWUVFLREFORFUwTXhFREFPQmdOVkJBc01CMU41YzBSbGRuTXhFVEFQQmdOVkJBTU1DRXh2ClkyRnNSVWRCTVJvd0dBWUpLb1pJaHZjTkFRa0JGZ3QwWlhOMFFHTnpZeTVtYVRBZUZ3MHhPREE1TVRRd056UTMKTWpGYUZ3MHlNVEEyTVRBd056UTNNakZhTUg0eEN6QUpCZ05WQkFZVEFrWkpNUkF3RGdZRFZRUUlEQWRHYVc1cwpZVzVrTVE0d0RBWURWUVFIREFWRmMzQnZiekVNTUFvR0ExVUVDZ3dEUTFORE1SQXdEZ1lEVlFRTERBZFRlWE5FClpYWnpNUkV3RHdZRFZRUUREQWhNYjJOaGJFVkhRVEVhTUJnR0NTcUdTSWIzRFFFSkFSWUxkR1Z6ZEVCamMyTXUKWm1rd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUUM4bHVlaE1uN25Id2EvVUNqSgpHZGlpZXEyT0ZCZFF1Z0FnaDBaYjNsZ2JWMFAxTncxZmlJS2VoclFHSkUvZFgrOUpIZXoweVRYd0RlVEt3czBMCmpjYzN6UzdFbVJhaGxkd096YjlPWDVwNjdISHBaYmovT084NDF1cnZFQXkrUjgzRHpSaWFCaUFvbkZOSndIOUIKb2NrazBkcjlKa3RmN2Z4R3BGS2ZWalNaNlZ2OHROMi9KVXZBYnlsMjI5aEpCaXFzczRSMVpZa2hVSFExN0tDaQoxQXRzMXBIVHdDZjh1ZVlQVHoyUkl1VlQ1M2hVWVRTa3h3VmtBTU5QaGt6N1hMRUxYU2VyRHpqUmZKUG5hZnpzCkZGOG9TNjVFWnZRQVpPWVN5c1dsMklzK05HZ1R6bk4yMXcxUGhuaUkxdzJjRmZXb09mVE5LK21tKzhhMTkvTzQKcmQrckFnTUJBQUdqR0RBV01CUUdBMVVkRVFRTk1BdUNDV3h2WTJGc2FHOXpkREFOQmdrcWhraUc5dzBCQVFzRgpBQU9DQVFFQVJOSkpQemg2WGdjUVNCWFU3M2JZVkt6UmtSeUpRVGtNOHc4Z01COE1LNi9XYk9LcjJhZnZYcmQrClpoZWpVUUVxS3FONmNSenpJZjdsZ1N3UDdsaXU3WkJTNHozVG16MXYydk9CN2NVS25QV3M1cW1WM1RPQjlobVYKUFNEUTJKQ3BRRkV1N0JRcmI1UVZTdUNwQ2FzSXNXYzVZQlVaT0V6K3JFQ1ZkZkY3Z29zSnM5RGhpc1I5WE5rbwowYk83cERRSmkycmJTbEtoNS9LNlk1KzEwQ1N1K1lzOWI4YUZ2b3daTFpRYVJqRTIyNUhuVzFGSHpzZUNuOXJwCjJPbHRLRlJ4S3JzZDV2VnhlOTFXaHdNQjFscmc3UkdZa0ZYdnladW9PZ09NSVlnRFNxNDhFZ1VrNTBHSW80SXYKTHI4VmRTYkN1OG1oZFo2a3pid0F6cG1lcXNXa0VRPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=" | base64 -d > ega-charts/localega/config/ssl.cert
      script:
        - set +e
        - kubectl cluster-info
        # Install fake CEGA
        - helm install --name travis-cega-$TRAVIS_BUILD_NUMBER --namespace travis-$TRAVIS_BUILD_NUMBER ega-charts/cega/ --set secrets.cega_creds=$CEGA_CREDS --wait --timeout 300
        # install LocalEGA
        - helm install --name travis-lega-$TRAVIS_BUILD_NUMBER --namespace travis-$TRAVIS_BUILD_NUMBER ega-charts/localega --set config.broker_username="$MQUSER",config.cega_users_host="http://cega-users",config.cega_mq_host="cega-mq",config.cega_username="lega",config.cega_vhost="lega",config.data_storage_url="http://rook-ceph-rgw-my-store.rook-ceph",config.postgres_user="lega",secrets.cega_creds="$CEGA_CREDS",secrets.cega_mq_pass="$CEGA_MQ_PASS",secrets.pgp_passphrase="$PGP_PASSWORD",secrets.shared_password="$SHARED_PASSWORD",secrets.mq_password="$MQ_PASSWORD",secrets.postgres_password="$POSTGRES_PASWORD",secrets.s3_access_key="$MINIO_ACCESS",secrets.s3_secret_key="$MINIO_SECRET" --wait --timeout 300
        # Upgrade helm deployment to use mina-inbox
        - helm upgrade travis-lega-$TRAVIS_BUILD_NUMBER --namespace travis-$TRAVIS_BUILD_NUMBER ega-charts/localega --set inbox.repository="nbisweden/ega-mina-inbox",config.broker_username="$MQUSER",config.cega_users_host="http://cega-users",config.cega_mq_host="cega-mq",config.cega_username="lega",config.cega_vhost="lega",config.data_storage_url="http://rook-ceph-rgw-my-store.rook-ceph",config.postgres_user="lega",secrets.cega_creds="$CEGA_CREDS",secrets.cega_mq_pass="$CEGA_MQ_PASS",secrets.pgp_passphrase="$PGP_PASSWORD",secrets.shared_pgp_password="$SHARED_PASSWORD",secrets.mq_password="$MQ_PASSWORD",secrets.postgres_password="$POSTGRES_PASWORD",secrets.s3_access_key="$MINIO_ACCESS",secrets.s3_secret_key="$MINIO_SECRET" --wait --timeout 300
        - helm delete --purge travis-cega-$TRAVIS_BUILD_NUMBER travis-lega-$TRAVIS_BUILD_NUMBER
        - kubectl delete ns travis-$TRAVIS_BUILD_NUMBER
      # make sure we clean up the kubernetes environment if things should fail.
      after_failure:
        - helm delete --purge travis-cega-$TRAVIS_BUILD_NUMBER travis-lega-$TRAVIS_BUILD_NUMBER
        - kubectl delete ns travis-$TRAVIS_BUILD_NUMBER
    - stage: publish
      env:
        - TARGET_BR=gh-pages
        - REPO_DIR=/home/travis/build/NBISweden/LocalEGA-helm
        - GH_URL=https://nbisweden.github.io/LocalEGA-helm/
      install:
        # Installing Helm
        - curl https://raw.githubusercontent.com/kubernetes/helm/v2.12.2/scripts/get > get_helm.sh && chmod 700 get_helm.sh && ./get_helm.sh
        - helm init --client-only
      before_script:
        # Decrypt key
        - >
          openssl aes-256-cbc
          -K $encrypted_key
          -iv $encrypted_iv
          -in .ssh-keys/travis.enc
          -out .ssh-keys/travis
          -d
        # Add the keypair to the agent
        - chmod 600 .ssh-keys/travis
        - eval "$(ssh-agent -s)"
        - ssh-add .ssh-keys/travis
      script:
        # Temporary dir for storing new packaged ega-charts and index files
        - BUILD_DIR=$(mktemp -d)

        # Useful URLs
        - REPO_URL=`git config remote.origin.url`
        - SSH_REPO=${REPO_URL/https:\/\/github.com\//git@github.com:}
        - SHA=`git rev-parse --verify HEAD`

        # Push temporary directory to the stack
        - pushd $BUILD_DIR

        # Iterate over all ega-charts and package them
        - >
          for dir in `ls ${REPO_DIR}/ega-charts`; do
            helm dep update ${REPO_DIR}/ega-charts/$dir
            helm package ${REPO_DIR}/ega-charts/$dir
          done

        # Indexing of ega-charts
        - >
          if [ -f index.yaml ]; then
            helm repo index --url ${GH_URL} --merge index.yaml .
          else
            helm repo index --url ${GH_URL} .
          fi

        # Pop temporary directory from the stack
        - popd

        # List all the contents that we will push
        - ls ${BUILD_DIR}

        # Clone repository and empty target branch
        - git clone ${REPO_URL} out
        - cd out
        - git checkout ${TARGET_BR} || git checkout --orphan ${TARGET_BR}
        - cd ..

        # Copying contents of BUILD_DIR to out folder
        - cp $BUILD_DIR/* out/
        - cd out
        # Add all new files to staging phase and commit the changes
        - git config user.name "Travis CI"
        - git config user.email "travis@travis-ci.org"
        - git add -A .
        - git status
        - git commit -m "Travis deploy ${SHA}"
        # We can push.
        - git push ${SSH_REPO}
