apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-archvie
spec:
  capacity:
    storage: 10Gi
### volumeMode field requires BlockVolume Alpha feature gate to be enabled.
##volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /ega/archive
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: node-role.kubernetes.io/master
          operator: In
          values:
          - "true"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: local-archive
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 10Gi