{{ if .Values.deploy.cega }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "localega.fullname" . }}-cega-users
  labels:
    app: cega-users
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: cega-users
{{ end }}