apiVersion: v1
kind: Service
metadata:
  name: {{ template "localega.fullname" . }}-filedatabase
  labels:
    app: {{ template "localega.name" . }}-filedatabase
spec:
  ports:
  - name: filedatabase
    port: {{ .Values.filedatabase.servicePort }}
    targetPort: {{ .Values.filedatabase.port }}
    protocol: TCP
  - name: filedatabase-debug
    port: {{ .Values.filedatabase.debug }}
    targetPort: {{ .Values.filedatabase.debug }}
    protocol: TCP 
  selector:
    app: {{ template "localega.name" . }}-filedatabase