apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "localega.fullname" . }}-inbox
  labels:
    role: inbox
    app: {{ template "localega.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.ingest.name }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  serviceName: inbox
  selector:
    matchLabels:
      app: inbox
  template:
    metadata:
      labels:
        app: inbox
        role: inbox
    spec:
      containers:
      - name: inbox
        image: "{{ .Values.inbox.repository }}:{{ .Values.inbox.imageTag }}"
        imagePullPolicy: {{ .Values.inbox.imagePullPolicy | quote }}
        env:
        - name: BROKER_HOST
          value: mq.localega.svc.cluster.local
        - name: INBOX_PORT
          value: "2222"
        - name: CEGA_ENDPOINT
          value: http://cega-users/user/
        - name: CEGA_ENDPOINT_CREDS
          valueFrom:
            secretKeyRef:
              name: {{ template "localega.name" . }}-cega-creds
              key: credentials
        ports:
        - name: inbox
          containerPort: 2222
          protocol: TCP
        volumeMounts:
        - name: lega-inbox
          mountPath: /ega/inbox
      volumes:
      - name: lega-inbox
      {{- if .Values.persistence.enabled }}
        {{- if .Values.inbox.persistence.storageClass }}
        {{ if (eq "flexVolume" .Values.inbox.persistence.storageClass) }}
        flexVolume:
          driver: {{ .Values.inbox.persistence.flexVolume.driver | quote }}
          fsType: {{ .Values.inbox.persistence.flexVolume.fsType | quote }}
          options:
            fsName: {{ .Values.inbox.persistence.flexVolume.fsName | quote }}
            clusterNamespace:  {{ .Values.inbox.persistence.flexVolume.clusterNamespace | quote }}
        {{ else if (eq "nfs" .Values.inbox.persistence.storageClass) }}
        source:
          nfs:
            server: {{ if .Values.inbox.persistence.nfs.server }}{{ .Values.inbox.persistence.nfs.server | quote }}{{ end }}
            path: {{ if .Values.inbox.persistence.nfs.path }}{{ .Values.inbox.persistence.nfs.path | quote }}{{- else }}{{ "/" }}{{- end }}
            readOnly: false
        {{ end }}
        {{ end }}
        {{ if .Values.inbox.existingClaim }}
        persistentVolumeClaim:
          claimName: {{ .Values.inbox.existingClaim }}
        {{ end }}
      {{ else}}
        emptyDir: {}
      {{ end }}
