{{ if eq "nbisweden/ega-inbox" .Values.inbox.repository }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "localega.fullname" . }}-inbox
  labels:
    role: inbox
    app: {{ template "localega.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.inbox.name }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  serviceName: inbox
  selector:
    matchLabels:
      app: {{ template "localega.name" . }}-inbox
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "localega.name" . }}-inbox
        role: inbox
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: inbox
        image: "{{ .Values.inbox.repository }}:{{ .Values.inbox.imageTag }}"
        imagePullPolicy: {{ .Values.inbox.imagePullPolicy | quote }}
        env:
        - name: BROKER_CONNECTION_ATTEMPTS
          value: {{ .Values.config.broker_connection_attempts | quote }}
        - name: BROKER_HOST
          value: {{ if .Values.config.broker_host }}{{ .Values.config.broker_host | quote }}{{ else }}{{ template "localega.fullname" . }}-mq{{ end }}
        - name: BROKER_PORT
          value: {{.Values.mq.port | quote }}
        - name: BROKER_RETRY_DELAY
          value: {{ .Values.config.broker_retry_delay | quote }}
        - name: BROKER_USERNAME
          value: {{ .Values.config.broker_username | quote }}
        - name: CEGA_ENDPOINT
          value: {{ required "A valid .values.config.cega_endpoint URL are required" .Values.config.cega_endpoint | quote }}
        - name: CEGA_ENDPOINT_JSON_PREFIX
          value: {{ .Values.config.cega_endpoint_json | quote }}
        - name: CEGA_ENDPOINT_CREDS
          valueFrom:
            secretKeyRef:
              name: {{ template "localega.name" . }}-cega-creds
              key: credentials
        ports:
        - name: inbox
          containerPort: 9000
          protocol: TCP
        volumeMounts:
        - name: lega-inbox
          mountPath: /ega/inbox
      volumes:
      - name: lega-inbox
      {{- if .Values.persistence.enabled }}
        {{ if (eq "flexVolume" .Values.inbox.persistence.storageClass) }}
        flexVolume:
          driver: {{ .Values.inbox.persistence.flexVolume.driver | quote }}
          fsType: {{ .Values.inbox.persistence.flexVolume.fsType | quote }}
          options:
            fsName: {{ .Values.inbox.persistence.flexVolume.fsName | quote }}
            clusterNamespace:  {{ .Values.inbox.persistence.flexVolume.clusterNamespace | quote }}
        {{ else if (eq "nfs" .Values.inbox.persistence.storageClass) }}
        source:
          nfs:
            server: {{ if .Values.inbox.persistence.nfs.server }}{{ .Values.inbox.persistence.nfs.server | quote }}{{ end }}
            path: {{ if .Values.inbox.persistence.nfs.path }}{{ .Values.inbox.persistence.nfs.path | quote }}{{- else }}{{ "/" }}{{- end }}
            readOnly: false
        {{ end }}
        {{ if .Values.inbox.existingClaim }}
        persistentVolumeClaim:
          claimName: {{ .Values.inbox.existingClaim }}
        {{ end }}
      {{ else}}
        emptyDir: {}
      {{ end }}
{{ end }}