apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "localega.ingest.fullname" . }}
  labels:
    app: {{ template "localega.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.ingest.name }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.ingest.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "localega.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "localega.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.base.image }}:{{ .Values.base.imageTag }}"
          imagePullPolicy: {{ .Values.base.imagePullPolicy | quote }}
          command: ["gosu", "lega", "ega-ingest"]
          env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ template "localega.name" . }}-db-secret
                key: postgres_password
          - name: LEGA_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ template "localega.name" . }}-password
                key: password
          - name: S3_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: {{ template "localega.name" . }}-s3-keys
                key: access_key
          - name: S3_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: {{ template "localega.name" . }}-s3-keys
                key: secret_key
          volumeMounts:
          - name: inbox
            mountPath: /ega/inbox
          - name: ingest-conf
            mountPath: /etc/ega
          ports:
          - name: inbox
            containerPort: 2222
      restartPolicy: Always
      volumes:
      - name: ingest-conf
        configMap:
          name: {{ template "localega.name" . }}-config
          items:
            - key: conf.ini
              path: conf.ini
          defaultMode: 0744
      - name: inbox
      {{- if .Values.persistence.enabled }}
        {{- if (eq "rook-ceph-block" .Values.persistence.storageClass) }}
        flexVolume:
          driver: ceph.rook.io/rook
          fsType: ceph
          options:
            fsName: sharedfs
            clusterNamespace: rook-ceph
        {{ else }}
        persistentVolumeClaim:
          claimName: {{ if .Values.inbox.existingClaim }}{{ .Values.inbox.existingClaim }}{{- else }}{{ template "localega.inbox.fullname" . }}{{- end }}
        {{ end }}
      {{ else}}
        emptyDir: {}
      {{ end }}