{{ if .Values.keys.deploy }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "localega.fullname" . }}-keys
  labels:
    app: {{ template "localega.name" . }}-keys
    role: keyserver
spec:
  ports:
  - port: 8443
    targetPort: 8443
    protocol: TCP
  selector:
    app: {{ template "localega.name" . }}-keys
{{ end }}