{{ if .Values.keys.deploy }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "localega.fullname" . }}-keys
  labels:
    role: keyserver
    app: {{ template "localega.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.keys.name }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  revisionHistoryLimit: {{ default "3" .Values.revisionHistory }}
  selector:
    matchLabels:
      app: {{ template "localega.name" . }}-keys
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "localega.name" . }}-keys
        role: keyserver
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: keyserver
        image: "{{ .Values.keys.repository }}:{{ .Values.keys.imageTag }}"
        imagePullPolicy: {{ .Values.keys.imagePullPolicy | quote }}
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: no-oss
        - name: EGA_KEY_PATH
          value: /etc/ega/key.1.sec
        - name: EGA_SHAREDPASS_PATH
          value: /etc/ega/pgp/password
        - name: EGA_PUBLICKEY_URL
          value: /etc/ega/ssl.key
        - name: EGA_KEYPASS_PATH
          value: /etc/ega/key/password
        - name: EGA_LEGACY_PATH
          value:
        - name: DB_USERNAME
          value: {{ .Values.config.postgres_user | quote }}
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "localega.name" . }}-db-secret
              key: postgres_password
        - name: DB_URL
          value: {{ if .Values.config.postgres_host }}{{ .Values.config.postgres_host | quote }}{{ else }}{{ template "localega.fullname" . }}-db{{ end }}
        ports:
        - name: key-app-port
          containerPort: {{ .Values.keys.port }}
          protocol: TCP
        livenessProbe:
          tcpSocket:
            port: key-app-port
          initialDelaySeconds: 120
          periodSeconds: 30
        volumeMounts:
        - name: keyserver-conf
          mountPath: /etc/ega
        - name: res-shared-pass
          mountPath: /etc/ega/pgp
        - name: ega-key-pass
          mountPath: /etc/ega/key
      volumes:
        - name: res-shared-pass
          secret:
            secretName: {{ template "localega.name" . }}-password
        - name: ega-key-pass
          secret:
            secretName: {{ template "localega.name" . }}-keypass 
        - name: keyserver-conf
          projected:
            sources:
            - configMap:
                name: {{ template "localega.name" . }}-config
                items:
                  - key: ssl.cert
                    path: ssl.cert
                  - key: ssl.key
                    path: ssl.key
                    mode: 0744
            - configMap:
                name: {{ template "localega.name" . }}-keyserver-secret
                items:
                  - key: key.1.sec
                    path: key.1.sec
{{ end }}