{{ if .Values.deploy.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "localega.name" . }}-db-secret
  labels:
    app: {{ template "localega.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  postgres_password: {{ .Values.secrets.postgres_password | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "localega.name" . }}-password
  labels:
  app: {{ template "localega.name" . }}
  chart: {{ .Chart.Name }}-{{ .Chart.Version }}
  release: {{ .Release.Name }}
  heritage: {{ .Release.Service }}
type: Opaque
data:
  password: {{ .Values.secrets.lega_password | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "localega.name" . }}-s3-keys
  labels:
  app: {{ template "localega.name" . }}
  chart: {{ .Chart.Name }}-{{ .Chart.Version }}
  release: {{ .Release.Name }}
  heritage: {{ .Release.Service }}
type: Opaque
data:
  access_key: {{ .Values.secrets.s3_access | b64enc }}
  secret_key: {{ .Values.secrets.s3_secret | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "localega.name" . }}-cega-creds
  labels:
  app: {{ template "localega.name" . }}
  chart: {{ .Chart.Name }}-{{ .Chart.Version }}
  release: {{ .Release.Name }}
  heritage: {{ .Release.Service }}
type: Opaque
data:
  credentials: {{ .Values.secrets.cega_creds | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "localega.name" . }}-cega-url
  labels:
  app: {{ template "localega.name" . }}
  chart: {{ .Chart.Name }}-{{ .Chart.Version }}
  release: {{ .Release.Name }}
  heritage: {{ .Release.Service }}
type: Opaque
data:
  url: {{ .Values.secrets.cega_address | b64enc }}
{{ end }}