{{ if and .Values.persistence.enabled ( eq "local-storage" .Values.persistence.storageClass ) (not .Values.inbox.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "localega.inbox.fullname" . }}
spec:
  storageClassName: {{ default "local-storage" .Values.persistence.storageClass | quote }} 
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ default "local-storage"  .Values.inbox.persistence.storageSize | quote }}
{{ end }}
---
{{ if and  .Values.persistence.enabled ( not .Values.postgres.persistence.existingClaim ) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "localega.postgres.fullname" . }}
spec:
  storageClassName: "{{ default "local-storage" .Values.persistence.storageClass }}"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ default "local-storage" .Values.postgres.persistence.storageSize | quote }}
{{ end }}
---
{{- if and .Values.persistence.enabled (not .Values.mq.existingClaim)}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: {{ template "localega.mq.fullname" . }}
spec:
  storageClassName: "{{ .Values.persistence.storageClass }}"
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ default "local-storage" .Values.mq.persistence.storageSize | quote }}
{{ end }}