apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "localega.fullname" . }}-mapper
  labels:
    role: mapper
    app: {{ template "localega.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.mapper.name }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "localega.name" . }}-mapper
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "localega.name" . }}-mapper
        role: mapper
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: mapper
        image: "{{ .Values.base.image }}:{{ .Values.base.imageTag }}"
        imagePullPolicy: {{ .Values.base.imagePullPolicy | quote }}
        command: ["gosu", "lega", "ega-id-mapper"]
        env:
        - name: BROKER_HOST
          value: {{ if .Values.config.broker_host }}{{ .Values.config.broker_host | quote }}{{ else }}{{ template "localega.fullname" . }}-mq{{ end }}
        - name: BROKER_CONNECTION_ATTEMPTS
          value: {{ .Values.config.broker_connection_attempts | quote }}
        - name: BROKER_PORT
            value: {{.Values.mq.port | quote }}
        - name: BROKER_RETRY_DELAY
          value: {{ .Values.config.broker_retry_delay | quote }}
      restartPolicy: Always
