{{ if .Values.config.deploy }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "localega.name" . }}-mq-config
  labels:
    app: {{ template "localega.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{ ( .Files.Glob "config/rabbitmq.config" ).AsConfig | indent 2 }}
{{ ( .Files.Glob "config/defs.json" ).AsConfig | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "localega.name" . }}-mq-entrypoint
  labels:
    app: {{ template "localega.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{ ( .Files.Glob "conf/mq.sh" ).AsConfig | indent 2 }}
{{ end }}