{{ if .Values.deploy.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "localega.name" . }}-db-config
  labels:
    app: {{ template "localega.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  user: lega
  dbname: lega
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "localega.name" . }}-initsql
  labels:
    app: {{ template "localega.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{ ( .Files.Glob "conf/*.sql" ).AsConfig | indent 2 }}
{{ end }}