apiVersion: v1
kind: Service
metadata:
  name: {{ template "localega.fullname" . }}-db
  labels:
    app: {{ template "localega.name" . }}-db
spec:
  ports:
    - name: postgresql
      port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: {{ template "localega.name" . }}-db
