apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "localega.fullname" . }}-verify
  labels:
    role: verify
    app: {{ template "localega.name" . }}
spec:
  replicas: 1
  serviceName: verify
  selector:
    matchLabels:
      app: verify
  template:
    metadata:
      labels:
        app: verify
        role: verify
    spec:
      containers:
      - name: verify
        image: "{{ .Values.base.image }}:{{ .Values.base.imageTag }}"
        imagePullPolicy: {{ .Values.base.imagePullPolicy | quote }}
        command: ["gosu", "lega", "ega-verify"]
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ template "localega.name" . }}-db-secret
                key: postgres_password
          - name: LEGA_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ template "localega.name" . }}-password
                key: password
          - name: S3_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: {{ template "localega.name" . }}-s3-keys
                key: access_key
          - name: S3_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: {{ template "localega.name" . }}-s3-keys
                key: secret_key
        volumeMounts:
        - name: verify-conf
          mountPath: /etc/ega
      restartPolicy: Always
      volumes:
      - name: verify-conf
        configMap:
          name: {{ template "localega.name" . }}-config
          items:
            - key: conf.ini
              path: conf.ini
          defaultMode: 0744
