{{- if (.Values.postgres.metrics.enabled) and .Values.postgres.deploy }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: postges-prometheus
  namespace: monitoring
  labels:
    prometheus: kube-prometheus
spec:
  jobLabel: {{ template "localega.name" . }}-db
  selector:
    matchLabels:
      app: {{ template "localega.name" . }}-db
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  endpoints:
    - port: metrics
      interval: 30s
{{ end }}