# Default values for localega.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
base:
  image: egarchive/lega-base
  imageTag: latest
  imagePullPolicy: Always

persistence: 
  enabled: true

secrets:
  cega_users_pass: 

mq:
  name: mq
  repository: rabbitmq
  imageTag: 3.6-management-alpine
  imagePullPolicy: IfNotPresent
  replicaCount: 1
  persistence:
    existingClaim: ""
    storageSize: 1Gi
