# Default values for localega.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
## does the cluster have rbac enabled? assume yes by default
rbacEnabled: true

podSecurityPolicy:
  create: true

persistence: 
  enabled: true

tls: true

mq:
  name: mq
  repository: rabbitmq
  imageTag: 3.7.8-management-alpine
  imagePullPolicy: IfNotPresent
  replicaCount: 1
  persistence:
    existingClaim: ""
    storageSize: 2Gi
  insecure: true

users:
  image: egarchive/lega-base
  imageTag: release.v0.2.0
  imagePullPolicy: Always
