apiVersion: v1
kind: Service
metadata:
  name: {{ template "cega.name" . }}-users
  labels:
    app: cega-users
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: cega-users
