apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "cega.fullname" . }}-mq
  labels:
    role: broker
    app: cega-mq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cega-mq
  template:
    metadata:
      labels:
        app: cega-mq
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/cegamq-secret.yaml") . | sha256sum }}
    spec:
    {{- if .Values.rbacEnabled}}
      serviceAccountName: cega
    {{- end }}
      securityContext:
        runAsUser: 100
        runAsGroup: 101
        fsGroup: 101
      containers:
      - name: cega-mq
        image: "{{ .Values.mq.repository }}:{{ .Values.mq.imageTag }}"
        imagePullPolicy: {{ .Values.mq.imagePullPolicy | quote }}
        securityContext:
         allowPrivilegeEscalation: false
        env:
        - name: RABBITMQ_CONFIG_FILE
          value: /etc/rabbitmq/conf/cega
        - name: RABBITMQ_ENABLED_PLUGINS_FILE
          value: /etc/rabbitmq/conf/cega.plugins
        ports:
        - containerPort: 15671
          protocol: TCP
          name: https
        {{- if .Values.mq.insecure }}
        - containerPort: 15672
          protocol: TCP
          name: http
        - containerPort: 5672
          name: amqp
        {{- end }}
        - containerPort: 5671
          name: amqps
        volumeMounts:
        - name: conf
          mountPath: /etc/rabbitmq/conf
        - name: rabbitmq
          mountPath: /var/lib/rabbitmq
        - name: ssl-certs
          mountPath: /etc/rabbitmq/ssl
      volumes:
      - name: ssl-certs
        secret:
          secretName: {{ template "cega.fullname" . }}-mq-certs
          defaultMode: 0440
      - name: conf
        secret:
          secretName: {{ template "cega.fullname" . }}-mq-config
          defaultMode: 0440
      - name: rabbitmq
      {{- if .Values.persistence.enabled }}
        {{- if .Values.mq.persistence.existingClaim }}
        persistentVolumeClaim:
          claimName: {{ .Values.mq.persistence.existingClaim }}
        {{- else }}
        persistentVolumeClaim:
          claimName: {{ template "cega.fullname" . }}-rabbitmq
        {{ end }}
      {{- else }}
        emptyDir: {}
      {{ end }}
