apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "cega.fullname" . }}-mq
  labels:
    role: broker
    app: cega-mq
spec:
  replicas: 1
  serviceName: "cega-mq"
  selector:
    matchLabels:
      app: cega-mq
  template:
    metadata:
      labels:
        app: cega-mq
    spec:
      containers:
      - name: cega-mq
        image: "{{ .Values.mq.repository }}:{{ .Values.mq.imageTag }}"
        imagePullPolicy: {{ .Values.mq.imagePullPolicy | quote }}
        command: ["/scripts/cega-mq.sh"]
        ports:
        - containerPort: 15671
          protocol: TCP
          name: https
        {{- if .Values.mq.insecure }}
        - containerPort: 15672
          protocol: TCP
          name: http
        - containerPort: 5672
          name: amqp
        {{- end }}
        - containerPort: 5671
          name: amqps
        volumeMounts:
        - name: cega-mq-entrypoint
          mountPath: /scripts
        - name: temp
          mountPath: /temp
        - name: rabbitmq
          mountPath: /etc/rabbitmq
        - name: ssl-certs
          mountPath: /etc/rabbitmq/ssl
      volumes:
      - name: ssl-certs
        secret:
          secretName: {{ template "cega.fullname" . }}-mq-certs
      - name: cega-mq-entrypoint
        configMap:
          name: {{ template "cega.fullname" . }}-mq-entrypoint
          defaultMode: 0744
      - name: temp
        configMap:
          name: {{ template "cega.fullname" . }}-mq-config
          items:
            - key: cega.json
              path: defs.json
            - key: cega.conf
              path: rabbitmq.conf
          defaultMode: 0744
      - name: rabbitmq
      {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ template "cega.fullname" . }}-rabbitmq
      {{ else}}
        emptyDir: {}
      {{ end }}
