{{- if and .Values.persistence.enabled (not .Values.mq.persistence.existingClaim) }}
{{ if .Values.persistence.storageClass }}
{{ if "local-storage" .Values.persistence.storageClass }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cega-rabbitmq-pv
  labels:
    type: local-storage
spec:
  storageClassName: {{ .Values.persistence.storageClass | quote }}
  claimRef:
    namespace: {{ .Release.Namespace }}
    name: {{ template "cega.fullname" . }}-rabbitmq
  capacity:
    storage: {{ .Values.mq.persistence.storageSize | quote }}
  accessModes:
    - {{ .Values.mq.persistence.accessModes | quote }}
  hostPath:
    path: {{ default "/mnt/data/mq" .Values.mq.hostpath | quote }}
    type: DirectoryOrCreate
{{ end }}
{{ end }}
{{ end }}
