apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "cega.fullname" . }}-users
  labels:
    role: fake-users
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cega-users
  template:
    metadata:
      labels:
        app: cega-users
        role: fake-users
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/cega-secret.yaml") . | sha256sum }}
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: cega-users
        image: "{{ .Values.users.image }}:{{ .Values.users.imageTag }}"
        imagePullPolicy: {{ .Values.users.imagePullPolicy | quote }}
        command: ["python", "/cega/users.py", "0.0.0.0", "8443", "/cega/users.json"]
        env:
          - name: LEGA_INSTANCES
            value: legatest
          - name: CEGA_USERS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ template "cega.fullname" . }}-creds
                key: credentials
          - name: CEGA_USERS_USER
            value: {{ required "Username for CEGA is needed " .Values.config.cega_users_user }}
        ports:
        - name: cega-users
          containerPort: 443
          protocol: TCP
        volumeMounts:
        - name: cega-config
          mountPath: /cega
        - name: cega-certs
          mountPath: /tls/
      volumes:
        - name: cega-config
          secret:
            secretName: {{ template "cega.fullname" . }}-users-config
            defaultMode: 0440
        - name: cega-certs
          secret:
            secretName: {{ template "cega.fullname" . }}-users-certs
            defaultMode: 0440
