apiVersion: v1
kind: Service
metadata:
  name: {{ template "cega.name" . }}-mq-management
  labels:
    app: cega-mq
spec:
  ports:
  {{- if .Values.mq.insecure }}
  - port: 15671
    targetPort: 15671
    protocol: TCP
    name: http
  {{- end }}
  - port: 15671
    targetPort: 15671
    protocol: TCP
    name: https
  selector:
    app: cega-mq
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "cega.name" . }}-mq
  labels:
    app: cega-mq
spec:
  ports:
  {{- if .Values.mq.insecure }}
  - port: 5672
    targetPort: 5672
    protocol: TCP
    name: amqp
  {{- end }}
  - port: 5671
    targetPort: 5671
    protocol: TCP
    name: amqps
  - port: 4369
    name: epmd
  - port: 25672
    name: rabbitmq-dist
  selector:
    app: cega-mq
