apiVersion: v1
kind: Secret
metadata:
  name: {{ template "cega.fullname" . }}-users-config
  labels:
    app: {{ template "cega.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{ ( .Files.Glob "config/users.*" ).AsSecrets | indent 2 }}
---
{{- if .Values.tls }}
{{- $cafile := .Files.Glob (printf "config/certs/%s" .Values.config.tls_ca_root_file)}}
{{- $cega := .Files.Glob "config/certs/cega-users.*" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "cega.fullname" . }}-users-certs
  labels:
    app: {{ template "cega.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{ ( $cafile ).AsSecrets | trim | indent 2 }}
{{ ( $cega ).AsSecrets | indent 2 }}
{{- end }}
