apiVersion: v1
kind: Secret
metadata:
  name: {{ template "cega.fullname" . }}-creds
  labels:
  app: {{ template "cega.name" . }}
  chart: {{ .Chart.Name }}-{{ .Chart.Version }}
  release: {{ .Release.Name }}
  heritage: {{ .Release.Service }}
type: Opaque
data:
  credentials: {{ .Values.secrets.cega_users_pass | quote | trimall "\"" | b64enc }}
---
{{- if .Values.tls }}
{{- $cafile := .Files.Glob (printf "conf/certs/%s" .Values.config.tls_ca_root_file)}}
{{- $cega_mq := .Files.Glob "conf/certs/cega-mq.*" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "cega.fullname" . }}-mq-certs
  labels:
    app: {{ template "cega.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{ ( $cafile ).AsSecrets | trim | indent 2 }}
{{ ( $cega_mq ).AsSecrets | indent 2 }}
{{- end }}