apiVersion: v1
kind: Secret
metadata:
  name: {{ template "cega.fullname" . }}-creds
  labels:
  app: {{ template "cega.name" . }}
  chart: {{ .Chart.Name }}-{{ .Chart.Version }}
  release: {{ .Release.Name }}
  heritage: {{ .Release.Service }}
type: Opaque
data:
  credentials: {{ .Values.secrets.cega_creds | quote | trimall "\"" | b64enc }}
