apiVersion: v1
kind: Secret
metadata:
  name: {{ template "cega.fullname" . }}-mq-config
  labels:
    app: {{ template "cega.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{ ( .Files.Glob "conf/cega.*" ).AsSecrets | indent 2 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "cega.fullname" . }}-mq-entrypoint
  labels:
    app: {{ template "cega.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{ ( .Files.Glob "conf/cega-mq.sh" ).AsSecrets | indent 2 }}
---
{{- if .Values.tls }}
{{- $cafile := .Files.Glob (printf "conf/certs/%s" .Values.config.tls_ca_root_file)}}
{{- $cega_mq := .Files.Glob "conf/certs/cega-mq.*" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "cega.fullname" . }}-mq-certs
  labels:
    app: {{ template "cega.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{ ( $cafile ).AsSecrets | trim | indent 2 }}
{{ ( $cega_mq ).AsSecrets | indent 2 }}
{{- end }}