
{{- if and .Values.rbacEnabled .Values.podSecurityPolicy.create }}
apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  name: cega-psp
  annotations:
   seccomp.security.alpha.kubernetes.io/defaultProfileName:  'docker/default'
   seccomp.security.alpha.kubernetes.io/allowedProfileNames: 'docker/default'
spec:
  requiredDropCapabilities:
    - ALL
  privileged: false
  allowPrivilegeEscalation: false
  defaultAllowPrivilegeEscalation: false
  hostNetwork: false
  hostPID: false
  hostIPC: false
  runAsUser:
    rule: MustRunAsNonRoot
  seLinux:
    rule: RunAsAny
  fsGroup:
    rule: MustRunAs
    ranges:
    - min: 100
      max: 65535
  supplementalGroups:
    rule: MustRunAs
    ranges:
    - min: 100
      max: 65535
  hostNetwork: false
  hostIPC: false
  hostPID: false
  #readOnlyRootFilesystem: true
  volumes:
  - secret
  - persistentVolumeClaim
  - configMap
  - emptyDir
{{- end }}
