{{- if .Values.rbacEnabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cega-psp-role
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - extensions
  resourceNames:
  - cega-psp
  resources:
  - podsecuritypolicies
  verbs:
  - use
{{- end }}
