# Default values for localega.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
base:
  image: nbisweden/ega-base
  imageTag: latest
  imagePullPolicy: Always

deploy:
  config: true
  secrets: true

persistence: 
  enabled: true

secrets:
  cega_address: ""
  cega_creds: ""
  cega_mq_pass: ""
  keys_password: ""
  lega_password: ""
  mq_password: ""
  postgres_password: ""
  s3_access: ""
  s3_secret: ""

mq:
  name: mq
  repository: rabbitmq
  imageTag: 3.6-management-alpine
  imagePullPolicy: IfNotPresent
  replicaCount: 1
  persistence:
    existingClaim: ""
    storageSize: 1Gi
