{{ if .Values.deploy.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "cega.fullname" . }}-users-config
  labels:
    app: {{ template "cega.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{ ( .Files.Glob "config/dummy.pub" ).AsConfig | indent 2 }}
{{ ( .Files.Glob "conf/*" ).AsConfig | indent 2 }}
{{ end }}