{{ if .Values.deploy.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "cega.fullname" . }}-mq-config
  labels:
    app: {{ template "cega.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{ ( .Files.Glob "config/cega.*" ).AsConfig | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "cega.fullname" . }}-mq-entrypoint
  labels:
    app: {{ template "cega.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{ ( .Files.Glob "conf/cega-mq.sh" ).AsConfig | indent 2 }}
{{ end }}