{{- if and .Values.config.tls_certs .Values.dataedge.deploy }}
{{- $cafile := .Files.Glob (printf "config/certs/%s" .Values.config.tls_ca_root_file)}}
{{- $javaca := .Files.Glob (printf "config/certs/cacerts") }}
{{- $dataedge := .Files.Glob "config/certs/dataedge*" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "localega.name" . }}-dataedge-certs
data:
{{ ( $cafile ).AsSecrets | trim | indent 2 }}
{{ ( $javaca ).AsSecrets | trim | indent 2 }}
{{ ( $dataedge ).AsSecrets | indent 2 }}
{{- end }} 