apiVersion: v1
kind: Service
metadata:
  name: {{ template "localega.name" . }}-dataedge
  labels:
    app: {{ template "localega.name" . }}-dataedge
spec:
  ports:
  - name: dataedge
    port: {{ .Values.dataedge.servicePort }}
    targetPort: {{ .Values.dataedge.port }}
    protocol: TCP
  - name: dataedge-debug
    port: {{ .Values.dataedge.debug }}
    targetPort: {{ .Values.dataedge.debug }}
    protocol: TCP
  selector:
    app: {{ template "localega.name" . }}-dataedge