{{- if and .Values.config.tls_certs .Values.filedatabase.deploy }}
{{- $cafile := .Files.Glob (printf "config/certs/%s" .Values.config.tls_ca_root_file) }}
{{- $javaca := .Files.Glob (printf "config/certs/cacerts") }}
{{- $filedb := .Files.Glob "config/certs/filedatabase*" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "localega.name" . }}-filedb-certs
  labels:
    app: {{ template "localega.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{ ( $cafile ).AsSecrets | trim | indent 2 }}
{{ ( $javaca ).AsSecrets | trim | indent 2 }}
{{ ( $filedb ).AsSecrets | indent 2 }}
{{- end }} 