{{- if and .Values.config.tls_certs .Values.finalize.deploy }}
{{- $cafile := .Files.Glob (printf "config/certs/%s" .Values.config.tls_ca_root_file) }}
{{- $finalize := .Files.Glob "config/certs/finalize*" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "localega.name" . }}-finalize-certs
data:
{{ ( $cafile ).AsSecrets | trim | indent 2 }}
{{ ( $finalize ).AsSecrets | indent 2 }}
{{- end }} 