apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "localega.fullname" . }}-finalize
  labels:
    role: finalize
    app: {{ template "localega.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.finalize.name }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  revisionHistoryLimit: {{ default "3" .Values.revisionHistory }}
  selector:
    matchLabels:
      app: {{ template "localega.name" . }}-finalize
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "localega.name" . }}-finalize
        role: finalize
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: finalize
        image: "{{ .Values.finalize.repository }}:{{ .Values.finalize.imageTag }}"
        imagePullPolicy: {{ .Values.finalize.imagePullPolicy | quote }}
        command: ["ega-finalize"]
        args: ["--log", {{ .Values.config.log | quote }}]
        env:
        - name: DEFAULT_LOG
          value: {{ .Values.config.log | quote }}
        - name: BROKER_CONNECTION_ATTEMPTS
          value: {{ .Values.config.broker_connection_attempts | quote }}
        - name: BROKER_ENABLE_SSL
          value: {{ .Values.config.broker_enable_ssl | quote }}
        - name: BROKER_HEARTBEAT
          value: {{ .Values.config.broker_heartbeat | quote }}
        - name: BROKER_HOST
          value: {{ if .Values.config.broker_host }}{{ .Values.config.broker_host | quote }}{{ else }}{{ template "localega.fullname" . }}-mq{{ end }}
        - name: BROKER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "localega.name" . }}-mq-pass
              key: password
        - name: BROKER_PORT
          value: {{.Values.mq.port | quote }}
        - name: BROKER_RETRY_DELAY
          value: {{ .Values.config.broker_retry_delay | quote }}
        - name: BROKER_USERNAME
          value: {{ .Values.config.broker_username | quote }}
        - name: BROKER_VHOST
          value: "/"
        - name: POSTGRES_HOST
          value: {{ if .Values.config.postgres_host }}{{ .Values.config.postgres_host | quote }}{{ else }}{{ template "localega.fullname" . }}-db{{ end }}
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "localega.name" . }}-db-secret
              key: pg_in_password
        - name: POSTGRES_PORT
          value: {{ .Values.config.postgres_port | quote }}
        - name: POSTGRES_SSLMODE
          value: {{ .Values.config.postgres_sslmode | quote }}
        - name: POSTGRES_SSLCERT
          value: ""
        - name: POSTGRES_TRY
          value: {{ .Values.config.postgres_try | quote }}
        - name: POSTGRES_TRY_INTERVAL
          value: {{ .Values.config.postgres_tryinterval | quote }}
        - name: POSTGRES_USER
          value: {{ .Values.config.postgres_in_user | quote }}
        resources:
{{ toYaml .Values.finalize.resources | indent 10 }}
      restartPolicy: Always
