apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "localega.fullname" . }}-finalize
  labels:
    role: finalize
    app: {{ template "localega.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.finalize.name }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  revisionHistoryLimit: {{ default "3" .Values.revisionHistory }}
  selector:
    matchLabels:
      app: {{ template "localega.name" . }}-finalize
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "localega.name" . }}-finalize
        role: finalize
        release: {{ .Release.Name }}
      annotations:
        checksum/conf: {{ include (print $.Template.BasePath "/finalize-conf.yaml") . | sha256sum }}
    spec:
      initContainers:
      - name: tls-init
        image: busybox
        command: ["/bin/sh", "-c"]
        args: ["/bin/cp /tls-certs/* /tls/ && chown 1000:1000 /tls/* && chmod 0400 /tls/*"]
        volumeMounts:
        - name: tls-certs
          mountPath: /tls-certs
        - name: tls
          mountPath: /tls
      containers:
      - name: finalize
        image: "{{ .Values.finalize.repository }}:{{ .Values.finalize.imageTag }}"
        imagePullPolicy: {{ .Values.finalize.imagePullPolicy | quote }}
        command: ["ega-finalize"]
        args: ["--log", {{ .Values.config.log | quote }}]
        env:
        - name: DEFAULT_LOG
          value: {{ .Values.config.log | quote }}
        resources:
{{ toYaml .Values.finalize.resources | trim | indent 10 }}
        volumeMounts:
        - name: conf
          mountPath: /etc/ega/
        - name: tls
          mountPath: "/etc/ega/ssl"
      volumes:
        - name: tls
          emptyDir:
            medium: Memory
            sizeLimit: 10Mi
        - name: tls-certs
          secret:
            secretName: {{ template "localega.name" . }}-finalize-certs
        - name: conf
          projected:
              sources:
              - configMap:
                  name: {{ template "localega.name" . }}-finalize-conf
      restartPolicy: Always
