{{- if .Values.finalize.deploy }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "localega.name" . }}-finalize-conf
  labels:
    app: {{ template "localega.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  conf.ini: |-
    [broker]
    connection = amqps://{{ .Values.config.broker_username }}:{{ .Values.secrets.mq_password }}@{{ template "localega.name" . }}-mq:{{ .Values.config.broker_port }}/%2f?heartbeat={{ .Values.config.broker_heartbeat }}&connection_attempts={{ .Values.config.broker_connection_attempts }}&retry_delay={{ .Values.config.broker_retry_delay }}
    verify_peer = true
    verify_hostname = false
    cacertfile = /etc/ega/ssl/{{ .Values.config.tls_ca_root_file }}
    certfile = /etc/ega/ssl/finalize{{ .Values.config.tls_cert_ending }}
    keyfile = /etc/ega/ssl/finalize{{ .Values.config.tls_key_ending }}
    [db]
    connection = postgres://{{ .Values.config.postgres_in_user }}:{{ .Values.secrets.pg_in_password }}@{{ template "localega.name" . }}-db:5432/lega?application_name=LocalEGA&sslmode={{ .Values.config.postgres_sslmode }}&sslcert=/etc/ega/ssl/finalize{{ .Values.config.tls_cert_ending }}&sslkey=/etc/ega/ssl/finalize{{ .Values.config.tls_key_ending }}&sslrootcert=/etc/ega/ssl/{{ .Values.config.tls_ca_root_file }}
    try = {{ .Values.config.postgres_try }}
    try_interval = {{ .Values.config.postgres_try_interval }}
{{- end }}