{{- if and .Values.config.tls_certs .Values.inbox.deploy }}
{{- $cafile := .Files.Glob (printf "config/certs/%s" .Values.config.tls_ca_root_file) }}
{{- $inbox := .Files.Glob "config/certs/inbox*" }}
{{- $javaca := .Files.Glob "config/certs/cacerts" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "localega.name" . }}-inbox-certs
  labels:
    app: {{ template "localega.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{ ( $cafile ).AsSecrets | trim | indent 2 }}
{{- if eq "nbisweden/ega-mina-inbox" .Values.inbox.repository }}
{{ ( $javaca ).AsSecrets | trim | indent 2 }}
{{- end }}
{{ ( $inbox ).AsSecrets | indent 2 }}
{{- end }} 