{{- if .Values.ingest.deploy }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "localega.ingest.fullname" . }}
  labels:
    app: {{ template "localega.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.ingest.name }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    role: ingest
spec:
  replicas: {{ .Values.ingest.replicaCount }}
  revisionHistoryLimit: {{ default "3" .Values.revisionHistory }}
  selector:
    matchLabels:
      app: {{ include "localega.name" . }}-ingest
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "localega.name" . }}-ingest
        role: ingest
        release: {{ .Release.Name }}
      annotations:
        checksum/conf: {{ include (print $.Template.BasePath "/ingest-conf.yaml") . | sha256sum }}
    spec:
    {{- if .Values.rbacEnabled}}
      serviceAccountName: {{ .Release.Name }}
    {{- end }}
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
{{- if or .Values.ingest.coLocateInbox }}
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: role
                operator: In
                values:
                - inbox
            topologyKey: "kubernetes.io/hostname"
{{- end }}
      initContainers:
      - name: tls-init
        image: busybox
        command: ["/bin/sh", "-c"]
        args: ["/bin/cp /tls-certs/* /tls/ && chown 1000:1000 /tls/* && chmod 0400 /tls/*"]
        securityContext:
          allowPrivilegeEscalation: false
        volumeMounts:
        - name: tls-certs
          mountPath: /tls-certs
        - name: tls
          mountPath: /tls
      containers:
      - name: ingest
        image: "{{ .Values.ingest.repository }}:{{ .Values.ingest.imageTag }}"
        imagePullPolicy: {{ .Values.ingest.imagePullPolicy | quote }}
        command: ["ega-ingest"]
        args: ["--log", {{ .Values.config.log | quote }}]
        securityContext:
          allowPrivilegeEscalation: false
        resources:
{{ toYaml .Values.ingest.resources | trim | indent 10 }}
        env:
        - name: DEFAULT_LOG
          value: {{ .Values.config.log | quote }}
        {{- if .Values.keys.deploy }}
        - name: LEGA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "localega.name" . }}-shared-password
              key: shared.pass
        {{- end }}
        volumeMounts:
        - name: lega-inbox
          mountPath: "/ega/inbox"
        - name: tls
          mountPath: "/etc/ega/ssl"
        - name: conf
          mountPath: /etc/ega/
        {{- if eq "FileStorage" .Values.config.data_storage_type }}
        - name: lega-archive
          mountPath: {{ .Values.config.data_storage_location | quote }}
        {{- end }}
      restartPolicy: Always
      volumes:
      - name: tls
        emptyDir:
          medium: Memory
          sizeLimit: 10Mi
      - name: tls-certs
        secret:
          defaultMode: 0440
          secretName: {{ template "localega.name" . }}-ingest-certs
      - name: conf
        projected:
          defaultMode: 0440
          sources:
          - configMap:
              name: {{ template "localega.name" . }}-ingest-conf
      - name: lega-inbox
      {{- if and .Values.inbox.persistence.existingClaim ( not .Values.s3inbox.deploy )}}
        persistentVolumeClaim:
          claimName: {{ if .Values.inbox.persistence.existingClaim }}{{ .Values.inbox.persistence.existingClaim }}{{ else }}{{ template "localega.inbox.fullname" . }}{{ end }}
      {{- else if (eq "flexVolume" .Values.inbox.persistence.storageClass) }}
        flexVolume:
          driver: {{ .Values.inbox.persistence.flexVolume.driver | quote }}
          fsType: {{ .Values.inbox.persistence.flexVolume.fsType | quote }}
          options:
            fsName: {{ .Values.inbox.persistence.flexVolume.fsName | quote }}
            clusterNamespace:  {{ .Values.inbox.persistence.flexVolume.clusterNamespace | quote }}
      {{- else if (eq "nfs" .Values.inbox.persistence.storageClass) }}
        nfs:
          server: {{ if .Values.inbox.persistence.nfs.server }}{{ .Values.inbox.persistence.nfs.server | quote }}{{ end }}
          path: {{ if .Values.inbox.persistence.nfs.path }}{{ .Values.inbox.persistence.nfs.path | quote }}{{ else }}{{ "/" }}{{ end }}
      {{- end }}
  {{- if eq "FileStorage" .Values.config.data_storage_type }}
      - name: lega-archive
      {{- if .Values.ingest.persistence.existingClaim }}
        persistentVolumeClaim:
          claimName: {{ .Values.ingest.persistence.existingClaim }}
      {{- else if (eq "flexVolume" .Values.ingest.persistence.storageClass) }}
        flexVolume:
          driver: {{ .Values.ingest.persistence.flexVolume.driver | quote }}
          fsType: {{ .Values.ingest.persistence.flexVolume.fsType | quote }}
          options:
            fsName: {{ .Values.ingest.persistence.flexVolume.fsName | quote }}
            clusterNamespace:  {{ .Values.ingest.persistence.flexVolume.clusterNamespace | quote }}
      {{- else if (eq "nfs" .Values.ingest.persistence.storageClass) }}
        nfs:
          server: {{ if .Values.ingest.persistence.nfs.server }}{{ .Values.ingest.persistence.nfs.server | quote }}{{ end }}
          path: {{ if .Values.ingest.persistence.nfs.path }}{{ .Values.ingest.persistence.nfs.path | quote }}{{ else }}{{ "/" }}{{ end }}
      {{- end }}
  {{- end }}
{{- end }}
