{{ if and .Values.config.tls_certs .Values.ingest.deploy }}
{{- $cafile := .Files.Glob (printf "config/certs/%s" .Values.config.tls_ca_root_file) }}
{{- $ingest := .Files.Glob "config/certs/ingest*" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "localega.name" . }}-ingest-certs
  labels:
    app: {{ template "localega.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{ ( $cafile ).AsSecrets | trim | indent 2 }}
{{ ( $ingest ).AsSecrets | indent 2 }}
{{ end }} 