{{ if .Values.keys.deploy }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "localega.fullname" . }}-keys
  labels:
    role: keyserver
    app: {{ template "localega.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.keys.name }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  revisionHistoryLimit: {{ default "3" .Values.revisionHistory }}
  selector:
    matchLabels:
      app: {{ template "localega.name" . }}-keys
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "localega.name" . }}-keys
        role: keyserver
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: keyserver
        image: "{{ .Values.keys.repository }}:{{ .Values.keys.imageTag }}"
        imagePullPolicy: {{ .Values.keys.imagePullPolicy | quote }}
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: no-oss
        - name: EGA_KEY_PATH
          value: /etc/ega/pgp/key.1.sec
        - name: EGA_KEYPASS_PATH
          value: /etc/ega/pgp/key.1.pass
        - name: EGA_SHAREDPASS_PATH
          value: /etc/ega/pgp/shared.pass
        - name: EGA_PUBLICKEY_URL
          value: /etc/ega/ssl/ssl.key
        - name: EGA_LEGACY_PATH
          value:
        - name: DB_USERNAME
          value: {{ .Values.config.postgres_user | quote }}
        - name: DB_PASSWORD
          valueFrom:
              secretKeyRef:
                name: {{ template "localega.name" . }}-db-secret
                key: postgres_password
        - name: DB_URL
          value: "jdbc:postgresql://{{ if .Values.config.postgres_host }}{{ .Values.config.postgres_host  }}{{ else }}{{ template "localega.fullname" . }}-db{{ end }}/{{ .Values.config.postgres_db_name }}"
        - name: FILEDATABASE_SERVERS
          value: "{{ if .Values.config.filedatabase_host }}{{ .Values.config.filedatabase_host }}:{{ .Values.filedatabase.servicePort }}{{ else }}{{ template "localega.fullname" . }}-filedatabase:{{ .Values.filedatabase.servicePort }}{{ end }}"
        ports:
        - name: key-app-port
          containerPort: {{ .Values.keys.port }}
          protocol: TCP
        livenessProbe:
          tcpSocket:
            port: key-app-port
          initialDelaySeconds: 120
          periodSeconds: 30
        resources:
{{ toYaml .Values.keys.resources | indent 10 }}
        volumeMounts:
        - name: keyserver-pgpkeys
          mountPath: /etc/ega/pgp
      volumes:
        - name: keyserver-pgpkeys
          projected:
            sources:
            - secret:
                name: {{ template "localega.name" . }}-keyserver-secret
                items:
                - key: key.1.sec
                  path: key.1.sec
            - secret:
                name: {{ template "localega.name" . }}-shared-password
                items:
                - key: shared.pass
                  path: shared.pass
            - secret:
                name: {{ template "localega.name" . }}-pgp-passphrase
                items:
                - key: pgp.pass
                  path: key.1.pass
{{ end }}