{{ if .Values.keys.deploy }}
{{- $pgpkey := .Files.Glob "config/key.1.sec" }}
{{ if $pgpkey -}}
{{- $sslkey := .Files.Glob "config/certs/ega_ssl.*" }}
{{ if $sslkey -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "localega.name" . }}-keyserver-secret
  labels:
    app: {{ template "localega.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{ ( $pgpkey ).AsSecrets | trim | indent 2 }}
{{ ( $sslkey ).AsSecrets | indent 2 }}
{{ end }}
{{ end }}
{{ end }}