
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "localega.name" . }}-db-secret
  labels:
    app: {{ template "localega.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  pg_in_password: {{ .Values.secrets.pg_in_password | quote | trimall "\"" | b64enc }}
  pg_out_password: {{ .Values.secrets.pg_out_password | quote | trimall "\"" | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "localega.name" . }}-shared-password
type: Opaque
data:
  shared.pass: {{ .Values.secrets.shared_pgp_password | quote | trimall "\"" | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "localega.name" . }}-pgp-passphrase
type: Opaque
data:
  pgp.pass: {{ .Values.secrets.pgp_passphrase | quote | trimall "\"" | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "localega.name" . }}-s3-keys
type: Opaque
data:
  s3_access_key: {{ .Values.secrets.s3_access_key | quote | trimall "\"" | b64enc }}
  s3_secret_key: {{ .Values.secrets.s3_secret_key | quote | trimall "\"" | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "localega.name" . }}-cega-users-creds
type: Opaque
data:
  credentials: {{ printf "%s:%s" .Values.config.cega_users_user .Values.secrets.cega_users_pass | quote | trimall "\"" | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "localega.name" . }}-cega-mq-connection
type: Opaque
data:
{{- if .Values.config.cega_mq_ssl }}
  cega_connection: {{ printf "amqps://%s:%s@%s:%s/%s?server_name_indication=%s" .Values.config.cega_mq_user .Values.secrets.cega_mq_pass (required "A valid cega MQ host is required" .Values.config.cega_mq_host) ( .Values.config.cega_port | quote | trimall "\"" ) .Values.config.cega_vhost .Values.config.cega_mq_host | quote | trimall "\"" | b64enc }}
{{- else }}
  cega_connection: {{ printf "amqp://%s:%s@%s:%s/%s" .Values.config.cega_mq_user .Values.secrets.cega_mq_pass (required "A valid cega MQ host is required" .Values.config.cega_mq_host) ( .Values.config.cega_port | quote | trimall "\"" ) .Values.config.cega_vhost | quote | trimall "\"" | b64enc }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "localega.name" . }}-mq-pass
type: Opaque
data:
  password: {{ .Values.secrets.mq_password | quote | trimall "\"" | b64enc }}
  password_hash: {{ .Values.secrets.mq_password_hash | quote | trimall "\"" | b64enc }}
