{{- if and .Values.persistence.enabled (not .Values.inbox.persistence.existingClaim) }}
{{- if .Values.persistence.storageClass }}
{{- if or ( eq "local-storage" .Values.persistence.storageClass ) ( eq "-" .Values.persistence.storageClass )}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: localega-inbox-pv
  labels:
    type: local-storage
spec:
  storageClassName: {{ .Values.persistence.storageClass | quote }} 
  claimRef:
    namespace: {{ .Release.Namespace }}
    name: {{ template "localega.inbox.fullname" . }}
  capacity:
    storage: {{ .Values.postgres.persistence.storageSize | quote }}
  accessModes:
    - ReadWriteMany
  {{- if ( eq "local-storage" .Values.persistence.storageClass)}}
  hostPath:
    path: "/mnt/data/inbox"
    type: DirectoryOrCreate
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
---
{{- if and .Values.persistence.enabled  (not .Values.postgres.persistence.existingClaim) }}
{{- if .Values.persistence.storageClass }}
{{- if or ( eq "local-storage" .Values.persistence.storageClass ) ( eq "-" .Values.persistence.storageClass )}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: localega-postgres-pv
  labels:
    type: local-storage
spec:
  storageClassName: {{ .Values.persistence.storageClass | quote }} 
  claimRef:
    namespace: {{ .Release.Namespace }}
    name: {{ template "localega.postgres.fullname" . }}
  capacity:
    storage: {{ .Values.postgres.persistence.storageSize | quote }}
  accessModes:
    - ReadWriteOnce
  {{- if ( eq "local-storage" .Values.persistence.storageClass)}}
  hostPath:
    path: "/mnt/data/db"
    type: DirectoryOrCreate
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
---
{{- if and .Values.persistence.enabled (not .Values.mq.persistence.existingClaim) }}
{{- if .Values.persistence.storageClass }}
{{- if or ( eq "local-storage" .Values.persistence.storageClass ) ( eq "-" .Values.persistence.storageClass )}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: localega-rabbitmq-pv
  labels:
    type: local-storage
spec:
  storageClassName: {{ .Values.persistence.storageClass | quote }} 
  claimRef:
    namespace: {{ .Release.Namespace }}
    name: {{ template "localega.mq.fullname" . }}
  capacity:
    storage: {{ .Values.mq.persistence.storageSize | quote }}
  accessModes:
    - ReadWriteOnce
  {{- if ( eq "local-storage" .Values.persistence.storageClass)}}
  hostPath:
    path: "/mnt/data/mq"
    type: DirectoryOrCreate
  {{- end }}
{{- end }}
{{- end }}
{{- end }}