
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "localega.name" . }}-db-secret
  labels:
    app: {{ template "localega.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  postgres_password: {{ .Values.secrets.postgres_password | quote | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "localega.name" . }}-password
  labels:
  app: {{ template "localega.name" . }}
  chart: {{ .Chart.Name }}-{{ .Chart.Version }}
  release: {{ .Release.Name }}
  heritage: {{ .Release.Service }}
type: Opaque
data:
  password: {{ .Values.secrets.lega_password | quote | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "localega.name" . }}-keypass
  labels:
  app: {{ template "localega.name" . }}
  chart: {{ .Chart.Name }}-{{ .Chart.Version }}
  release: {{ .Release.Name }}
  heritage: {{ .Release.Service }}
type: Opaque
data:
  password: {{ .Values.secrets.keys_password | quote | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "localega.name" . }}-s3-keys
  labels:
  app: {{ template "localega.name" . }}
  chart: {{ .Chart.Name }}-{{ .Chart.Version }}
  release: {{ .Release.Name }}
  heritage: {{ .Release.Service }}
type: Opaque
data:
  s3_access_key: {{ .Values.secrets.s3_access_key | quote | b64enc }}
  s3_secret_key: {{ .Values.secrets.s3_secret_key | quote | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "localega.name" . }}-cega-creds
  labels:
  app: {{ template "localega.name" . }}
  chart: {{ .Chart.Name }}-{{ .Chart.Version }}
  release: {{ .Release.Name }}
  heritage: {{ .Release.Service }}
type: Opaque
data:
  credentials: {{ printf "%s:%s" .Values.config.cega_username .Values.secrets.cega_creds | quote | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "localega.name" . }}-cega-mq-pass
  labels:
  app: {{ template "localega.name" . }}
  chart: {{ .Chart.Name }}-{{ .Chart.Version }}
  release: {{ .Release.Name }}
  heritage: {{ .Release.Service }}
type: Opaque
data:
  pass: {{ .Values.secrets.cega_mq_pass | quote | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "localega.name" . }}-mq-pass
  labels:
  app: {{ template "localega.name" . }}
  chart: {{ .Chart.Name }}-{{ .Chart.Version }}
  release: {{ .Release.Name }}
  heritage: {{ .Release.Service }}
type: Opaque
data:
  password: {{ .Values.secrets.mq_password | quote | b64enc }}