{{- if and .Values.config.tls_certs .Values.mq.deploy }}
{{- $cafile := .Files.Glob (printf "config/certs/%s" .Values.config.tls_ca_root_file) }}
{{- $mqcerts := .Files.Glob "config/certs/mq*" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "localega.name" . }}-mq-certs
data:
{{ ( $cafile ).AsSecrets | trim | indent 2 }}
{{ ( $mqcerts ).AsSecrets | indent 2 }}
{{- end }} 