{{- $mqconf := .Files.Glob "config/rabbitmq.config" }}
{{ if $mqconf }}
{{- $mqdef := .Files.Glob "config/defs.json" }}
{{ if $mqdef }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "localega.name" . }}-mq-config
  labels:
    app: {{ template "localega.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{ ( $mqconf ).AsConfig | indent 2 }}
{{ ( $mqdef ).AsConfig | indent 2 }}
{{ end }}
{{ end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "localega.name" . }}-mq-entrypoint
  labels:
    app: {{ template "localega.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{ ( .Files.Glob "conf/mq.sh" ).AsConfig | indent 2 }}