apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "localega.fullname" . }}-mq
  labels:
    role: broker
    app: {{ template "localega.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.mq.name }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  revisionHistoryLimit: {{ default "3" .Values.revisionHistory }}
  strategy:
    type: "Recreate"
  serviceName: mq
  selector:
    matchLabels:
      app: {{ template "localega.name" . }}-mq
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "localega.name" . }}-mq
        release: {{ .Release.Name }}
        role: broker
    spec:
      containers:
      - name: mq
        image: "{{ .Values.mq.repository }}:{{ .Values.mq.imageTag }}"
        imagePullPolicy: {{ .Values.mq.imagePullPolicy }}
        env:
          - name: MQ_USER
            value: {{.Values.config.broker_username | quote }}
          - name: MQ_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ template "localega.name" . }}-mq-pass
                key: password
          - name: MQ_PASSWORD_HASH
            valueFrom:
              secretKeyRef:
                name: {{ template "localega.name" . }}-mq-pass
                key: password_hash
          - name: CEGA_CONNECTION
            valueFrom:
              secretKeyRef:
                name: {{ template "localega.name" . }}-cega-mq-connection
                key: cega_connection
        ports:
        - name: lega-mq
          containerPort: 15672
          protocol: TCP
        - containerPort: {{.Values.mq.port}}
          name: amqp
        readinessProbe:
          tcpSocket:
            port: amqp
          initialDelaySeconds: 30
          periodSeconds: 15
        volumeMounts:
        - name: rabbitmq
          mountPath: /var/lib/rabbitmq
      {{- if .Values.mq.metrics.enabled }}
      - name: metrics
        image: "{{ .Values.mq.metrics.repository }}:{{ .Values.mq.metrics.imageTag }}"
        imagePullPolicy: {{ .Values.mq.metrics.imagePullPolicy | quote }}
        env:
        - name: RABBIT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "localega.name" . }}-mq-pass
              key: password
        - name: RABBIT_URL
          value: "http://localhost:15672"
        - name: RABBIT_USER
          value: {{ .Values.config.broker_username | quote }}
        ports:
        - name: metrics
          containerPort: 9090
        livenessProbe:
          httpGet:
            path: /metrics
            port: metrics
          initialDelaySeconds: 15
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /metrics
            port: metrics
          initialDelaySeconds: 5
          timeoutSeconds: 1
        resources:
  {{ toYaml .Values.mq.metrics.resources | indent 10 }}
      {{- end }}
      volumes:
{{- if and .Values.persistence.enabled .Values.mq.persistence.existingClaim }}
      - name: rabbitmq
        persistentVolumeClaim:
          claimName: {{ .Values.mq.persistence.existingClaim | quote }}
  {{- else if not .Values.persistence.enabled }}
      - name: rabbitmq
        emptyDir: {}
  {{- else if and .Values.persistence.enabled (not .Values.mq.persistence.existingClaim) }}
  volumeClaimTemplates:
  - metadata:
      name: rabbitmq
      labels:
        app: {{ template "localega.mq.fullname" . }}
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ .Values.postgres.persistence.storageSize }}
    {{- if .Values.persistence.storageClass }}
      storageClassName: {{ .Values.persistence.storageClass | quote}}
    {{ end }}
  {{- end -}}
