apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "localega.fullname" . }}-mq
  labels:
    role: broker
    app: {{ template "localega.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.mq.name }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  revisionHistoryLimit: {{ default "3" .Values.revisionHistory }}
  strategy:
    type: "Recreate"
  serviceName: mq
  selector:
    matchLabels:
      app: {{ template "localega.name" . }}-mq
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "localega.name" . }}-mq
        release: {{ .Release.Name }}
        role: broker
    spec:
      securityContext:
        runAsUser: 100
        fsGroup: 101
        allowPrivilegeEscalation: false
      containers:
      - name: mq
        image: "{{ .Values.mq.repository }}:{{ .Values.mq.imageTag }}"
        imagePullPolicy: {{ .Values.mq.imagePullPolicy }}
        env:
          - name: MQ_USER
            value: {{.Values.config.broker_username | quote }}
          - name: MQ_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ template "localega.name" . }}-mq-pass
                key: password
          - name: MQ_PASSWORD_HASH
            valueFrom:
              secretKeyRef:
                name: {{ template "localega.name" . }}-mq-pass
                key: password_hash
          - name: CEGA_CONNECTION
            valueFrom:
              secretKeyRef:
                name: {{ template "localega.name" . }}-cega-mq-connection
                key: cega_connection
          {{- if .Values.config.tls_certs }}
          - name: MQ_CA
            value: /etc/rabbitmq/tls/{{ .Values.config.tls_ca_root_file }}
          - name: MQ_SERVER_CERT
            value: /etc/rabbitmq/tls/mq-server{{ .Values.config.tls_cert_ending }}
          - name: MQ_SERVER_KEY
            value: /etc/rabbitmq/tls/mq-server{{ .Values.config.tls_key_ending }}
          {{- end }}
        ports:
        - containerPort: 15672
          name: management
          protocol: TCP
        - containerPort: {{ .Values.config.broker_port }}
          name: amqp
        readinessProbe:
          tcpSocket:
            port: amqp
          initialDelaySeconds: 30
          periodSeconds: 15
        volumeMounts:
        - name: rabbitmq
          mountPath: /var/lib/rabbitmq/mnesia
        {{- if .Values.config.tls_certs }}
        - name: tls-certs
          mountPath: /etc/rabbitmq/tls
        {{- end }}
        {{- if .Values.mq.tls_client_certs }} 
        - name: client-certs
          mountPath: /etc/rabbitmq/ssl-client
        {{- end }}
      {{- if .Values.mq.metrics.enabled }}
      - name: metrics
        image: "{{ .Values.mq.metrics.repository }}:{{ .Values.mq.metrics.imageTag }}"
        imagePullPolicy: {{ .Values.mq.metrics.imagePullPolicy | quote }}
        env:
        - name: RABBIT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "localega.name" . }}-mq-pass
              key: password
        - name: RABBIT_URL
          value: "http://localhost:15672"
        - name: RABBIT_USER
          value: {{ .Values.config.broker_username | quote }}
        ports:
        - name: metrics
          containerPort: 9090
        livenessProbe:
          httpGet:
            path: /metrics
            port: metrics
          initialDelaySeconds: 15
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /metrics
            port: metrics
          initialDelaySeconds: 5
          timeoutSeconds: 1
        resources:
  {{ toYaml .Values.mq.metrics.resources | trim | indent 10 }}
      {{- end }}
      volumes:
{{- if .Values.config.tls_certs }}
      - name: tls-certs
        secret:
          defaultMode: 0440
          secretName: {{ template "localega.name" . }}-mq-certs
{{- end }}
{{- if .Values.mq.tls_client_certs }}
      - name: client-certs
        secret:
          defaultMode: 0440
          secretName: mq-client-certs
{{- end }}
{{- if and .Values.persistence.enabled .Values.mq.persistence.existingClaim }}
      - name: rabbitmq
        persistentVolumeClaim:
          claimName: {{ .Values.mq.persistence.existingClaim | quote }}
  {{- else if not .Values.persistence.enabled }}
      - name: rabbitmq
        emptyDir: {}
  {{- else if and .Values.persistence.enabled (not .Values.mq.persistence.existingClaim) }}
  volumeClaimTemplates:
  - metadata:
      name: rabbitmq
      labels:
        app: {{ template "localega.mq.fullname" . }}
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ .Values.mq.persistence.storageSize }}
    {{- if .Values.persistence.storageClass }}
      storageClassName: {{ .Values.persistence.storageClass | quote}}
    {{ end }}
  {{- end }}
