{{- if .Values.mq.deploy }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "localega.name" . }}-mq-management
  labels:
    app: {{ template "localega.name" . }}-mq-management
spec:
  ports:
  - port: 15672
    targetPort: 15672
    protocol: TCP
    name: http
  selector:
    app: {{ template "localega.name" . }}-mq
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "localega.name" . }}-mq
  labels:
    app: {{ template "localega.name" . }}-mq
spec:
  ports:
  - port: {{ .Values.config.broker_port }}
    targetPort: {{ .Values.config.broker_port }}
    name: amqp
  - port: 4369
    name: epmd
  - port: 25672
    name: rabbitmq-dist
  {{- if .Values.mq.metrics.enabled }}
  - name: metrics
    port: 9090
    targetPort: 9090
  {{- end }}
  selector:
    app: {{ template "localega.name" . }}-mq
{{- end }}