{{- if .Values.networkPolicy.create }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
  namespace: {{ .Release.Namespace }}
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-dns-access
  namespace: {{ .Release.Namespace }}
spec:
  podSelector: {}
  policyTypes:
  - Egress
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: kube-system
    ports:
    - protocol: UDP
      port: 53
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: dataedge
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app: localega-dataedge
  policyTypes:
  - Ingress
  - Egress
  egress:
    - to:
      - podSelector:
          matchLabels:
            app: localega-filedatabase
      - podSelector:
          matchLabels:
            app: localega-keys
      - podSelector:
          matchLabels:
            app: localega-res
  ingress:
    - ports:
      - port: dataedge
        protocol: TCP
      from:
      - ipBlock:
        cidr: 0.0.0.0/0
        except:
          - 10.0.0.0/8
          - 192.168.0.0/16
          - 172.16.0.0/20
      {{- if .Values.tester.run }}
      - podSelector:
          matchLabels:
            app: localega-tester
      {{- end }}
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: filedatabase
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app: localega-filedatabase
  policyTypes:
  - Ingress
  - Egress
  egress:
    - to:
      - podSelector:
          matchLabels:
            app: localega-db
  ingress:
    - ports:
      - port: filedatabase
        protocol: TCP
      from:
      - podSelector:
          matchLabels:
            app: localega-dataedge
{{- end }}