{{- if and .Values.config.tls_certs .Values.postgres.deploy }}
{{- $cafile := .Files.Glob (printf "config/certs/%s" .Values.config.tls_ca_root_file) }}
{{- $dbcerts := .Files.Glob "config/certs/db*" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "localega.name" . }}-db-certs
data:
{{ ( $cafile ).AsSecrets | trim | indent 2 }}
{{ ( $dbcerts ).AsSecrets | indent 2 }}
{{- end }} 