{{ if .Values.postgres.deploy }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "localega.name" . }}-db
  labels:
    app: {{ template "localega.name" . }}-db
  {{- if .Values.postgres.metrics.enabled }}
    prometheus: kube-prometheus
  {{- end }}
spec:
  ports:
    - name: postgresql
      port: {{ .Values.postgres.servicePort }}
      targetPort: {{ .Values.postgres.port }}
      protocol: TCP
  {{- if .Values.postgres.metrics.enabled }}
    - name: metrics
      port: 9187
      targetPort: 9187
  {{- end }}
  selector:
    app: {{ template "localega.name" . }}-db
{{ end }}