{{- if .Values.res.deploy }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "localega.name" . }}-res
  labels:
    app: {{ template "localega.name" . }}-res
spec:
  ports:
  - name: res-app-port
    port: {{ .Values.res.servicePort }}
    targetPort: {{ .Values.res.port }}
    protocol: TCP
  - name: res-debug-port
    port: {{ .Values.res.debug }}
    targetPort: {{ .Values.res.debug }}
    protocol: TCP
  selector:
    app: {{ template "localega.name" . }}-res
{{- end }}