{{- if and .Values.config.tls_certs .Values.res.deploy }}
{{- $cafile := .Files.Glob (printf "config/certs/%s" .Values.config.tls_ca_root_file) }}
{{- $javaca := .Files.Glob (printf "config/certs/cacerts") }}
{{- $res := .Files.Glob "config/certs/res*" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "localega.name" . }}-res-certs
data:
{{ ( $cafile ).AsSecrets | trim | indent 2 }}
{{ ( $javaca ).AsSecrets | trim | indent 2 }}
{{ ( $res ).AsSecrets | indent 2 }}
{{- end }} 