{{ if .Values.config.tls_certs }}
{{- $cafile := .Files.Glob (printf "config/certs/%s" .Values.config.tls_ca_root_file) }}
{{- $res := .Files.Glob "config/certs/res*" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "localega.name" . }}-res-certs
  labels:
    app: {{ template "localega.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{ ( $cafile ).AsSecrets | trim | indent 2 }}
{{ ( $res ).AsSecrets | indent 2 }}
{{ end }} 