{{- if .Values.s3proxy.deploy }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "localega.fullname" . }}-s3proxy
  labels:
    role: s3proxy
    app: {{ template "localega.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.s3proxy.name }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  revisionHistoryLimit: {{ default "3" .Values.revisionHistory }}
  selector:
    matchLabels:
      app: {{ template "localega.name" . }}-s3proxy
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "localega.name" . }}-s3proxy
        role: s3proxy
        release: {{ .Release.Name }}
      annotations:
        checksum/conf: {{ include (print $.Template.BasePath "/s3proxy-certs.yaml") . | sha256sum }}
      {{- if .Values.s3proxy.use_credentials_file }}
        checksum/conf: {{ include (print $.Template.BasePath "/s3proxy-credentials.yaml") . | sha256sum }}
      {{ end }}
    spec:
    {{- if .Values.rbacEnabled }}
      serviceAccountName: {{ .Release.Name }}
    {{- end }}
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: s3proxy
        image: "{{ .Values.s3proxy.repository }}:{{ .Values.s3proxy.imageTag }}"
        imagePullPolicy: {{ .Values.s3proxy.imagePullPolicy | quote }}
        command: ["s3proxy"]
        args: ["--log", {{ .Values.config.log | quote }}]
        securityContext:
          allowPrivilegeEscalation: false
        env:
      {{- if not .Values.s3proxy.use_config_file }}
        - name: AWS_URL
          value: {{ .Values.config.s3_proxy_url | quote }}
        - name: AWS_ACCESSKEY
          value: {{ .Values.secrets.s3_proxy_access_key | quote }}
        - name: AWS_SECRETKEY
          value: {{ .Values.secrets.s3_proxy_secret_key | quote }}
        - name: AWS_REGION
          value: {{ .Values.config.s3_proxy_region | quote }}
        - name: AWS_BUCKET
          value: {{ .Values.config.s3_proxy_bucket | quote }}
        - name: BROKER_HOST
          value: {{ if .Values.config.broker_host }}{{ .Values.config.broker_host | quote }}{{ else }}{{ template "localega.name" . }}-mq{{ end }}
        - name: BROKER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "localega.name" . }}-mq-pass
              key: password
        - name: BROKER_PORT
          value: {{ .Values.config.broker_port | quote }}
        - name: BROKER_USER
          value: {{ .Values.config.broker_username | quote }}
        - name: BROKER_PASSWORD
          value: {{ .Values.secret.mq_password | quote }}
        - name: BROKER_VHOST
          value: "/"
        - name: BROKER_EXCHANGE
          value: "lega"
        - name: - BROKER_ROUTINGKEY
          value: "files.inbox"
        - name: BROKER_SSL
          value: "true"
        - name: BROKER_CACERT
          value: /etc/ega/ssl/{{ .Values.config.tls_ca_root_file }}
        - name: BROKER_CLIENTCERT
          value: /etc/ega/ssl/s3inbox{{ .Values.config.tls_cert_ending }}
        - name: BROKER_CLIENTKEY
          value: /etc/ega/ssl/s3imnbox{{ .Values.config.tls_key_ending }}
      {{ end }}
        resources:
{{ toYaml .Values.s3proxy.resources | trim | indent 10 }}
        volumeMounts:
        - name: tls
          mountPath: /etc/ega/ssl
        {{- if .Values.s3proxy.use_config_file }}
        - name: config
          mountPath: /
        {{ end }}
      volumes:
        - name: tls
          secret:
            secretName: {{ template "localega.name" . }}-s3proxy-certs
        - name: ca-cert
          projected:
            defaultMode: 0460
            sources:
            - secret:
                name: {{ template "localega.name" . }}-s3proxy-certs
                items:
                  - key: .Values.config.tls_ca_root_file
                    path: /etc/ssl/certs/lega-ca.pem
      {{- if .Values.s3proxy.use_credentials_file }}
        - name: config
          secret:
            secretName: {{ template "localega.name" . }}-s3proxy-config
      {{ end }}
      restartPolicy: Always
{{- end }}
