{{- if and .Values.s3proxy.use_credentials_file .Values.s3proxy.deploy }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "localega.name" . }}-s3proxy-credentials
data:
  credentials: |-
    [default]
    aws_access_key_id = {{ .Values.secrets.s3_proxy_access_key }}
    aws_secret_access_key = {{ .Values.secrets.s3_proxy_secret_access_key }}
{{- end }}
