{{- if .Values.rbacEnabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: {{ template "localega.fullname" . }}-serviceAccount
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
{{- end }}