apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "localega.fullname" . }}-verify
  labels:
    role: verify
    app: {{ template "localega.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.verify.name }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  revisionHistoryLimit: {{ default "3" .Values.revisionHistory }}
  serviceName: verify
  selector:
    matchLabels:
      app: {{ template "localega.name" . }}-verify
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "localega.name" . }}-verify
        role: verify
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: verify
        image: "{{ .Values.verify.repository }}:{{ .Values.verify.imageTag }}"
        imagePullPolicy: {{ .Values.verify.imagePullPolicy | quote }}
        command: ["gosu", "lega", "ega-verify"]
        args: ["--log", {{ .Values.config.log | quote }}]
        env:
        - name: DEFAULT_LOG
          value: {{ .Values.config.log | quote }}
        - name: BROKER_CONNECTION_ATTEMPTS
          value: {{ .Values.config.broker_connection_attempts | quote }}
        - name: BROKER_ENABLE_SSL
          value: {{ .Values.config.broker_enable_ssl | quote }}
        - name: BROKER_HEARTBEAT
          value: {{ .Values.config.broker_heartbeat | quote }}
        - name: BROKER_HOST
          value: {{ if .Values.config.broker_host }}{{ .Values.config.broker_host | quote }}{{ else }}{{ template "localega.fullname" . }}-mq{{ end }}
        - name: BROKER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "localega.name" . }}-mq-pass
              key: password
        - name: BROKER_PORT
          value: {{.Values.mq.port | quote }}
        - name: BROKER_RETRY_DELAY
          value: {{ .Values.config.broker_retry_delay | quote }}
        - name: BROKER_USERNAME
          value: {{ .Values.config.broker_username | quote }}
        - name: BROKER_VHOST
          value: "/"
        - name: POSTGRES_HOST
          value: {{ if .Values.config.postgres_host }}{{ .Values.config.postgres_host | quote }}{{ else }}{{ template "localega.fullname" . }}-db{{ end }}
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "localega.name" . }}-db-secret
              key: postgres_password
        - name: POSTGRES_SSLMODE
          value: {{ .Values.config.postgres_sslmode | quote }}
        - name: POSTGRES_SSLCERT
          value: ""
        - name: POSTGRES_TRY
          value: {{ .Values.config.postgres_try | quote }}
        - name: POSTGRES_USER
          value: {{ .Values.config.postgres_user | quote }}
        - name: QUALITY_CONTROL_KEYSERVER_ENDPOINT
          value: {{ if .Values.config.keyserver_host }}{{ .Values.config.keyserver_host }}{{ else }}http://{{ template "localega.fullname" . }}-keys{{ end }}:{{ .Values.keys.servicePort }}{{ .Values.config.keyserver_endpoint }}
        - name: QUALITY_CONTROL_VERIFY_CERTIFICATE
          value: "false"
        - name: VAULT_DRIVER
          value: {{ .Values.config.data_storage_type | quote }}
{{ if eq "S3Storage" .Values.config.data_storage_type }}
        - name: VAULT_BUCKET
          value: {{ .Values.config.data_storage_s3_bucket | quote }}
        - name: VAULT_REGION
          value: {{ .Values.config.data_storage_s3_region | quote }}
        - name: S3_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: {{ template "localega.name" . }}-s3-keys
              key: s3_access_key
        - name: S3_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: {{ template "localega.name" . }}-s3-keys
              key: s3_secret_key
        - name: VAULT_CHUNK_SIZE
          value: {{  .Values.config.data_storage_s3_chunk_size | mul 1048576 | quote }}
        - name: VAULT_URL
          value: {{ required "A valid .Values.config.data_storage_url entry required!" .Values.config.data_storage_url | quote }}
{{ else if eq "FileStorage" .Values.config.data_storage_type}}
        - name: VAULT_LOCATION
          value: {{ .Values.config.data_storage_location | quote }}
        - name: VAULT_MODE
          value: {{ .Values.config.data_storage_mode | quote }}
{{ end }}
        - name: LEGA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "localega.name" . }}-shared-password
              key: shared.pass
        resources:
{{ toYaml .Values.verify.resources | indent 10 }}
      restartPolicy: Always