{{- if and .Values.config.tls_certs .Values.verify.deploy }}
{{- $cafile := .Files.Glob (printf "config/certs/%s" .Values.config.tls_ca_root_file) }}
{{- $verify := .Files.Glob "config/certs/verify*" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "localega.name" . }}-verify-certs
data:
{{ ( $cafile ).AsSecrets | trim | indent 2 }}
{{ ( $verify ).AsSecrets | indent 2 }}
{{- end }} 