apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "localega.fullname" . }}-verify
  labels:
    role: verify
    app: {{ template "localega.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.verify.name }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  revisionHistoryLimit: {{ default "3" .Values.revisionHistory }}
  serviceName: verify
  selector:
    matchLabels:
      app: {{ template "localega.name" . }}-verify
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "localega.name" . }}-verify
        role: verify
        release: {{ .Release.Name }}
      annotations:
        checksum/conf: {{ include (print $.Template.BasePath "/verify-conf.yaml") . | sha256sum }}
    spec:
      initContainers:
      - name: tls-init
        image: busybox
        command: ["/bin/sh", "-c"]
        args: ["/bin/cp /tls-certs/* /tls/ && chown 1000:1000 /tls/* && chmod 0400 /tls/*"]
        volumeMounts:
        - name: tls-certs
          mountPath: /tls-certs
        - name: tls
          mountPath: /tls
      containers:
      - name: verify
        image: "{{ .Values.verify.repository }}:{{ .Values.verify.imageTag }}"
        imagePullPolicy: {{ .Values.verify.imagePullPolicy | quote }}
        command: ["ega-verify"]
        args: ["--log", {{ .Values.config.log | quote }}]
        env:
        - name: LEGA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "localega.name" . }}-shared-password
              key: shared.pass
        resources:
{{ toYaml .Values.verify.resources | trim | indent 10 }}
        volumeMounts:
        - name: conf
          mountPath: /etc/ega/
        - name: tls
          mountPath: /etc/ega/ssl
        {{- if eq "FileStorage" .Values.config.data_storage_type }}
        - name: lega-archive
          mountPath: /ega/archive
        {{- end }}
      volumes:
        - name: tls-certs
          secret:
            secretName: {{ template "localega.name" . }}-verify-certs
        - name: tls
          emptyDir:
            medium: Memory
            sizeLimit: 10Mi
        - name: conf
          configMap:
            name: {{ template "localega.name" . }}-verify-conf
      {{- if eq "FileStorage" .Values.config.data_storage_type }}
        - name: lega-archive
          hostPath:
            path: {{ .Values.config.data_storage_location | quote }}
            type: Directory
      {{- end }}
      restartPolicy: Always