apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: minio-psp-role
rules:
- apiGroups:
  - extensions
  resourceNames:
  - minio-psp
  resources:
  - podsecuritypolicies
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: minio-psp-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: minio-psp-role
subjects:
- kind: ServiceAccount
  name: minio
---
apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  name: minio-psp
  annotations:
   seccomp.security.alpha.kubernetes.io/defaultProfileName:  'docker/default'
   seccomp.security.alpha.kubernetes.io/allowedProfileNames: 'docker/default'
spec:
  requiredDropCapabilities:
    - ALL
  privileged: false
  allowPrivilegeEscalation: false
  defaultAllowPrivilegeEscalation: false
  hostNetwork: false
  hostPID: false
  hostIPC: false
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  fsGroup:
    rule: MustRunAs
    ranges:
    - min: 1
      max: 65535
  supplementalGroups:
    rule: MayRunAs
    ranges:
    - min: 1
      max: 65535
  hostNetwork: false
  hostIPC: false
  hostPID: false
  volumes:
  - emptyDir
  - secret
  - persistentVolumeClaim
  - configMap
  - projected