# Default values for localega.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
base:
  image: nbisweden/ega-base
  imageTag: latest
  imagePullPolicy: Always

config:
#  broker_host: "localega-mq"
  broker_connection_attempts: 30
  broker_retry_delay: 10
  eureka_endpoint: "http://localhost:8761"
  keyserver_endpoint: "'https://$KEYSERVER_HOST:$KEYSERVER_PORT/retrieve/%s/private'"
#  keyserver_host: "0.0.0.0"
#  keyserver_port: 8443
#  postgres_host: "localega-db"
  postgres_try: 30
  postgres_user: "lega"
  vault_driver: "S3Storage"
  vault_url: ""

deploy:
  config: true
  secrets: true

persistence: 
  enabled: true
## Persistent Volume Storage Class
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ##   set, choosing the default provisioner.

secrets:
  cega_creds: ""
  cega_mq_pass: ""
  keys_password: ""
  lega_password: ""
  mq_password: ""
  postgres_password: ""
  s3_access: ""
  s3_secret: ""

inbox:
  name: inbox
  repository: nbisweden/ega-mina-inbox
  imageTag: latest
  imagePullPolicy: IfNotPresent
  inboxPath: ""
  replicaCount: 1
  persistence:
    existingClaim: ""
    storageSize: 1Gi
    storageClass: flexVolume
    flexVolume:
      driver: ceph.rook.io/rook
      fsType: ceph
      fsName: sharedfs
      clusterNamespace: rook-ceph
  service:
    type: ClusterIP
    port: 2222


ingest:
  name: ingest
  replicaCount: 1

keys:
  name: keys
  replicaCount: 1
  port: 8443

mapper:
  name: mapper
  replicaCount: 1

mq:
  name: mq
  repository: rabbitmq
  imageTag: 3.6-management-alpine
  imagePullPolicy: IfNotPresent
  replicaCount: 1
  persistence:
    existingClaim: ""
    storageSize: 1Gi

postgres:
  name: db
  repository: postgres
  imageTag: 9.6-alpine
  imagePullPolicy: IfNotPresent
  persistence:
    existingClaim: ""
    storageSize: 1Gi
  replicaCount: 1

verify:
  name: verify
  replicaCount: 1
