# Default values for localega.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

config:
  log: "debug"
  broker_connection_attempts: 30
  broker_enable_ssl: true
  broker_heartbeat: 0
  broker_port: 5671
  broker_retry_delay: 1
  broker_username: "guest" # local broker user, currently set to "guest"
  cega_users_host: # http://cega-users-server-fqdn
  cega_mq_host: "" # FQDN to cega mq host
  cega_mq_ssl: true
  cega_vhost: "" # vhost for central ega MQ service without leading slash
  cega_port: 5671
  cega_users_user: "" # user for cega users service
  cega_mq_user: "" # user for cega MQ service
  postgres_pgdata: "/ega"
  postgres_db_name: "lega"
  postgres_host: "" # defaults to localega-db
  postgres_port: 5432
  postgres_try: 5
  postgres_try_interval: 1
  postgres_sslmode: "verify-ca"
  postgres_in_user: "lega_in"
  postgres_out_user: "lega_out"
  data_storage_type: "S3Storage" # S3Storage or FileStorege
# The four lines below is only used with S3 backend
  data_storage_url: "" # URl to S3 instance
  data_storage_s3_bucket: ""
  data_storage_s3_region: ""
  data_storage_s3_chunk_size: 16 # Chunk size in MB > 5
# The two lines below is only used with FileStorage
#  data_storage_location: "/ega/data_archive" # path to data archive volume
#  data_storage_mode: 2750
  tls_certs: true
  tls_cert_ending: ".crt"
  tls_key_ending: ".key"
  tls_ca_root_file: "ca.crt"

persistence: 
  enabled: true
## Persistent Volume Storage Class
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ##   set, choosing the default provisioner.

## RevisionHistory
##  If defined, set the revisionHistoryLimit of the deployment, defaults to 3
##  RevisionHistoryLimit is number of old ReplicaSets to retain to allow rollback.
# revisionHistory: 3

secrets:
  cega_users_pass: ""
  cega_mq_pass: ""
  pgp_passphrase: ""
  shared_pgp_password: ""
  mq_password: ""
  mq_password_hash: ""
  pg_out_password: ""
  pg_in_password: ""
  s3_access_key: ""
  s3_secret_key: ""
  token: ""

ingress:
  deploy: false
  hostName: ""
  tls: true
  secretName: ""
  # issuer requires a configured cert-manager
  issuer: ""

dataedge:
  name: dataedge
  repository: nbisweden/ega-dataedge
  imageTag: m7
  imagePullPolicy: IfNotPresent
  replicaCount: 1
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "1024Mi"
      cpu: "500m"
  port: 8080
  servicePort: 9059
  debug: 5058
  logpath: "/tmp/logs"
  keystorePass: "dataedge"
  ingress:
    path: "/dataedge"

filedatabase:
  name: filedatabase
  repository: nbisweden/ega-filedb
  imageTag: m7
  imagePullPolicy: IfNotPresent
  replicaCount: 1
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "1024Mi"
      cpu: "500m"
  port: 8080
  servicePort: 9050
  debug: 5050
  keystorePass: "filedb"

inbox:
  name: inbox
  repository: nbisweden/ega-mina-inbox
  imageTag: m7
  imagePullPolicy: IfNotPresent
  inboxPath: ""
  replicaCount: 1
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "250m"
  persistence:
    existingClaim: ""
    storageSize: 1Gi
    storageClass: ""
    flexVolume:
      driver: "" #ceph.rook.io/rook
      fsType: "" #ceph
      fsName: "" #sharedfs
      clusterNamespace: "" #rook-ceph
    nfs:
      server: ""
      path: ""
  location: "/ega/inbox" # path to inbox volume
  port: 9000
  service:
    type: ClusterIP
    port: 2222
  keystorePass: "inbox"

ingest:
  name: ingest
  replicaCount: 1
  repository: nbisweden/ega-base
  imageTag: m7
  imagePullPolicy: IfNotPresent
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "250m"
## co-locate inbox with ingest
# If the deployment requires the use of hostPath volumes for the shared filesystem
# that is used by inbox and ingest, set coLocateInbox: true
  coLocateInbox: false

keys:
  deploy: true
  name: keys
  repository: nbisweden/ega-keyserver
  imageTag: m7
  imagePullPolicy: IfNotPresent
  replicaCount: 1
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "1024Mi"
      cpu: "500m"
  port: 8080
  servicePort: 9095
  debug: 5054
  keystorePass: "keys"

finalize:
  name: finalize
  replicaCount: 1
  repository: nbisweden/ega-base
  imageTag: m7
  imagePullPolicy: IfNotPresent
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "250m"

mq:
  name: mq
  repository: nbisweden/ega-mq
  imageTag: m7
  imagePullPolicy: IfNotPresent
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "250m"
  persistence:
    existingClaim: ""
    storageSize: 2Gi
  metrics:
    enabled: false
    repository: kbudde/rabbitmq-exporter
    imageTag: v0.29.0
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        memory: 256Mi
        cpu: 100m

postgres:
  deploy: true
  name: db
  repository: nbisweden/ega-db
  imageTag: m7-v2
  imagePullPolicy: IfNotPresent
  port: 5432
  servicePort: 5432
  persistence:
    existingClaim: ""
    storageSize: 1Gi
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "250m"
  metrics:
    enabled: false
    repository: wrouesnel/postgres_exporter
    imageTag: v0.4.6
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        memory: 256Mi
        cpu: 100m

res:
  name: res
  repository: nbisweden/ega-res
  imageTag: m7
  imagePullPolicy: IfNotPresent
  replicaCount: 1
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "1024Mi"
      cpu: "500m"
  port: 8080
  servicePort: 9090
  debug: 5058
  keystorePass: "res"
  ingress:
    path: "/res"

verify:
  name: verify
  replicaCount: 1
  repository: nbisweden/ega-base
  imageTag: m7
  imagePullPolicy: IfNotPresent
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "250m"

tester:
  run: false
  name: tester
  log: "debug"
  size: "small"
  repository: nbisweden/localega-tester
  imageTag: m7
  imagePullPolicy: IfNotPresent
