name: k3s deployment

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Clone and install deploy-inint
      run: |
        git clone https://github.com/neicnordic/LocalEGA-deploy-init
        pip3 install LocalEGA-deploy-init/
        legainit --cega --config-path ega-charts/localega/config --svc-config .ssh-keys/init-conf.json --cega-svc-config .ssh-keys/init-conf.json
    - name: Install k3s
      run: curl -sfL https://get.k3s.io | sh -
    - name: Fix permissions & copy config file
      run: |
        sudo chmod 666 /etc/rancher/k3s/* 
        mkdir -p ~/.kube/ && cp /etc/rancher/k3s/k3s.yaml ~/.kube/config
    - name: Install helm3
      run: |
        wget https://get.helm.sh/helm-v3.0.0-linux-amd64.tar.gz -O - | tar -xz
        sudo cp linux-amd64/helm /usr/local/bin/helm
    - name: Helm add stable repo
      run: |
        helm repo add stable https://kubernetes-charts.storage.googleapis.com/
        helm repo update
    - name: Wait for k3s to become ready
      run: until kubectl -n kube-system get pods -lk8s-app=metrics-server -o jsonpath='{range .items[*]}{@.metadata.name}:{range @.status.conditions[*]}{@.type}={@.status}' | grep "Ready=True"; do echo "waiting for k3s to become ready"; sleep 10; done
    - name: Install minio
      run: |
        kubectl create secret generic minio-certs --from-file=ega-charts/localega/config/certs/s3.ca.crt --from-file=ega-charts/localega/config/certs/s3.ca.key
        MINIO_ACCESS=$(grep s3_access_key ega-charts/localega/config/trace.yml | awk {'print $2'} | sed --expression 's/\"//g')
        MINIO_SECRET=$(grep s3_secret_key ega-charts/localega/config/trace.yml | awk {'print $2'} | sed --expression 's/\"//g')
        helm install minio --set accessKey=$MINIO_ACCESS,secretKey=$MINIO_SECRET,minioConfig.region=lega,tls.enabled=true,tls.publicCrt=s3.ca.crt,tls.privateKey=s3.ca.key,tls.certSecret=minio-certs,persistence.size=1Gi stable/minio --version 2.5.18
    - name: Wait for minio to become ready
      run: until kubectl get pods -lapp=minio -o jsonpath='{range .items[*]}{@.metadata.name}:{range @.status.conditions[*]}{@.type}={@.status}' | grep "Ready=True"; do echo "waiting for minio to become ready"; sleep 10; done
    - name: Install fake CEGA
      run: |
        cp -r ega-charts/localega/config ega-charts/cega/config
        helm install cega ega-charts/cega/ -f ega-charts/cega/config/trace.yml --set podSecurityPolicy.create=false
    - name: Wait for CEGA to become ready
      run: |
        RETRY_TIMES=0
        until kubectl get pods -l app=cega-users -o jsonpath='{range .items[*]}{@.metadata.name}:{range @.status.conditions[*]}{@.type}={@.status}' | grep "Ready=True" || [ $RETRY_TIMES -eq 30 ] ; do echo "waiting for fake cega to become ready"; kubectl get pods ; RETRY_TIMES=$((RETRY_TIMES+1)); sleep 10; done
    - name: verify
      run: sleep 30 && kubectl get pods
