name: k3s deployment

on: [push,pull_request]

jobs:

  mina-inbox:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Clone and install deploy-init
      run: |
        git clone https://github.com/neicnordic/LocalEGA-deploy-init
        pip3 install LocalEGA-deploy-init/
        legainit --cega --config-path ega-charts/localega/config
    - name: Install k3s
      run: curl -sfL https://get.k3s.io | sh -
    - name: Fix permissions & copy config file
      run: |
        sudo chmod 666 /etc/rancher/k3s/* 
        mkdir -p ~/.kube/ && cp /etc/rancher/k3s/k3s.yaml ~/.kube/config
    - name: Install helm3
      run: |
        wget https://get.helm.sh/helm-v3.0.0-linux-amd64.tar.gz -O - | tar -xz
        sudo cp linux-amd64/helm /usr/local/bin/helm
    - name: Helm add stable repo
      run: |
        helm repo add stable https://kubernetes-charts.storage.googleapis.com/
        helm repo update
    - name: Wait for k3s to become ready
      run: until kubectl -n kube-system get pods -lk8s-app=metrics-server -o jsonpath='{range .items[*]}{@.metadata.name}:{range @.status.conditions[*]}{@.type}={@.status}' | grep "Ready=True"; do echo "waiting for k3s to become ready"; sleep 10; done
    - name: Install minio
      run: |
        kubectl create secret generic minio-certs --from-file=ega-charts/localega/config/certs/s3.ca.crt --from-file=ega-charts/localega/config/certs/s3.ca.key
        MINIO_ACCESS=$(grep s3_archive_access_key ega-charts/localega/config/trace.yml | awk {'print $2'} | sed --expression 's/\"//g')
        MINIO_SECRET=$(grep s3_archive_secret_key ega-charts/localega/config/trace.yml | awk {'print $2'} | sed --expression 's/\"//g')
        helm install minio \
        --set accessKey=$MINIO_ACCESS,secretKey=$MINIO_SECRET,\
        tls.enabled=true,tls.publicCrt=s3.ca.crt,tls.privateKey=s3.ca.key,tls.certSecret=minio-certs,\
        persistence.enabled=false,service.port=443 stable/minio --version 4.0.0
    - name: Wait for minio to become ready
      run: until kubectl get pods -lapp=minio -o jsonpath='{range .items[*]}{@.metadata.name}:{range @.status.conditions[*]}{@.type}={@.status}' | grep "Ready=True"; do echo "waiting for minio to become ready"; sleep 10; done
    - name: Create inbox path
      run: |
        sudo mkdir -p /ega/inbox
        sudo chown 1000:1000 /ega/inbox
    - name: Create inbox volume
      run: kubectl apply -f .ssh-keys/inbox-local-volume.yaml
    - name: Install fake CEGA
      run: |
        cp -r ega-charts/localega/config ega-charts/cega/config
        helm install cega ega-charts/cega/ -f ega-charts/cega/config/trace.yml --set podSecurityPolicy.create=false,persistence.enabled=false
    - name: Wait for CEGA to become ready
      run: |
        RETRY_TIMES=0
        until kubectl get pods -l app=cega-users -o jsonpath='{range .items[*]}{@.metadata.name}:{range @.status.conditions[*]}{@.type}={@.status}' | grep "Ready=True" || [ $RETRY_TIMES -eq 20 ];
        do echo "waiting for fake cega to become ready";
        RETRY_TIMES=$((RETRY_TIMES+1));
        if [ $RETRY_TIMES -eq 20 ]; then exit 1; fi
        sleep 10;
        done
    - name: Install LocalEGA
      run: |
        helm install lega ega-charts/localega/ -f ega-charts/localega/config/trace.yml \
        --set config.cega_users_host="https://cega-users",config.cega_mq_host="cega-mq",config.s3_archive_url="https://minio",\
        inbox.persistence.existingClaim=local-inbox,config.s3_archive_bucket=lega,config.s3_archive_ca="/ega/tls/root.ca.crt",\
        ingest.CoLocateInbox=true,podSecurityPolicy.create=false,persistence.enabled=false
    - name: Wait for LocalEGA to become ready
      run: |
        RETRY_TIMES=0
        until kubectl get pods -lrole=inbox -o jsonpath='{range .items[*]}{@.metadata.name}:{range @.status.conditions[*]}{@.type}={@.status}' | grep "Ready=True" || [ $RETRY_TIMES -eq 20 ];
        do echo "waiting for LocalEGA to become ready";
        RETRY_TIMES=$((RETRY_TIMES+1));
        if [ $RETRY_TIMES -eq 20 ]; then exit 1; fi
        sleep 10;
        done
    - name: Run e2e test
      run: |
        helm upgrade lega ega-charts/localega/ -f ega-charts/localega/config/trace.yml \
        --set config.cega_users_host="https://cega-users",config.cega_mq_host="cega-mq",config.s3_archive_url="https://minio",\
        inbox.persistence.existingClaim=local-inbox,config.s3_archive_bucket=lega,config.s3_archive_ca="/ega/tls/root.ca.crt",\
        ingest.CoLocateInbox=true,podSecurityPolicy.create=false,persistence.enabled=false,tester.run=true
    - name: Wait for e2e test to complete
      run: |
        RETRY_TIMES=0
        until kubectl get jobs localega-e2e-tester -o jsonpath='{.status.conditions[?(@.type=="Complete")].status}' | grep "True" || [ $RETRY_TIMES -eq 20 ] ; do echo "waiting for e2e-test to complete"; RETRY_TIMES=$((RETRY_TIMES+1)); sleep 10; done
        if [ $RETRY_TIMES -eq 20 ]; then exit 1; fi
    - name: show pods
      run: kubectl get pods


  s3inbox:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Clone and install deploy-init
      run: |
        git clone https://github.com/neicnordic/LocalEGA-deploy-init
        pip3 install LocalEGA-deploy-init/
        legainit --cega --config-path ega-charts/localega/config
    - name: Install k3s
      run: curl -sfL https://get.k3s.io | sh -
    - name: Fix permissions & copy config file
      run: |
        sudo chmod 666 /etc/rancher/k3s/* 
        mkdir -p ~/.kube/ && cp /etc/rancher/k3s/k3s.yaml ~/.kube/config
    - name: Install helm3
      run: |
        wget https://get.helm.sh/helm-v3.0.0-linux-amd64.tar.gz -O - | tar -xz
        sudo cp linux-amd64/helm /usr/local/bin/helm
    - name: Helm add stable repo
      run: |
        helm repo add stable https://kubernetes-charts.storage.googleapis.com/
        helm repo update
    - name: Wait for k3s to become ready
      run: until kubectl -n kube-system get pods -lk8s-app=metrics-server -o jsonpath='{range .items[*]}{@.metadata.name}:{range @.status.conditions[*]}{@.type}={@.status}' | grep "Ready=True"; do echo "waiting for k3s to become ready"; sleep 10; done
    - name: Install minio
      run: |
        kubectl create secret generic minio-certs --from-file=ega-charts/localega/config/certs/s3.ca.crt --from-file=ega-charts/localega/config/certs/s3.ca.key
        MINIO_ACCESS=$(grep s3_archive_access_key ega-charts/localega/config/trace.yml | awk {'print $2'} | sed --expression 's/\"//g')
        MINIO_SECRET=$(grep s3_archive_secret_key ega-charts/localega/config/trace.yml | awk {'print $2'} | sed --expression 's/\"//g')
        helm install minio \
        --set accessKey=$MINIO_ACCESS,secretKey=$MINIO_SECRET,\
        tls.enabled=true,tls.publicCrt=s3.ca.crt,tls.privateKey=s3.ca.key,tls.certSecret=minio-certs,\
        persistence.enabled=false,service.port=443  stable/minio --version 4.0.0
    - name: Wait for minio to become ready
      run: until kubectl get pods -lapp=minio -o jsonpath='{range .items[*]}{@.metadata.name}:{range @.status.conditions[*]}{@.type}={@.status}' | grep "Ready=True"; do echo "waiting for minio to become ready"; sleep 10; done
    - name: Create inbox volume
      run: kubectl apply -f .ssh-keys/inbox-local-volume.yaml
    - name: Install fake CEGA
      run: |
        cp -r ega-charts/localega/config ega-charts/cega/config
        helm install cega ega-charts/cega/ -f ega-charts/cega/config/trace.yml --set podSecurityPolicy.create=false,persistence.enabled=false
    - name: Wait for CEGA to become ready
      run: |
        RETRY_TIMES=0
        until kubectl get pods -l app=cega-users -o jsonpath='{range .items[*]}{@.metadata.name}:{range @.status.conditions[*]}{@.type}={@.status}' | grep "Ready=True" || [ $RETRY_TIMES -eq 20 ];
        do echo "waiting for fake cega to become ready";
        RETRY_TIMES=$((RETRY_TIMES+1));
        if [ $RETRY_TIMES -eq 20 ]; then exit 1; fi
        sleep 10;
        done
    - name: Install LocalEGA
      run: |
        helm install lega ega-charts/localega/ -f ega-charts/localega/config/trace.yml \
        --set config.cega_users_host="https://cega-users",config.cega_mq_host="cega-mq",inbox.deploy=false,\
        config.s3_archive_url="https://minio",config.s3_archive_bucket=lega,config.s3_archive_ca="/ega/tls/root.ca.crt",\
        s3inbox.deploy=true,config.s3_inbox_backend_url="https://minio",config.s3_inbox_backend_bucket=lega,\
        config.s3_inbox_backed_cacert="/etc/ega/ssl/root.ca.crt",podSecurityPolicy.create=false,persistence.enabled=false
    - name: Wait for LocalEGA to become ready
      run: |
        RETRY_TIMES=0
        until kubectl get pods -lrole=doa -o jsonpath='{range .items[*]}{@.metadata.name}:{range @.status.conditions[*]}{@.type}={@.status}' | grep "Ready=True" || [ $RETRY_TIMES -eq 20 ];
        do echo "waiting for localega to become ready";
        RETRY_TIMES=$((RETRY_TIMES+1));
        if [ $RETRY_TIMES -eq 20 ]; then exit 1; fi
        sleep 10;
        done
    - name: Run e2e test
      run: |
        helm upgrade lega ega-charts/localega/ -f ega-charts/localega/config/trace.yml \
        --set config.cega_users_host="https://cega-users",config.cega_mq_host="cega-mq",inbox.deploy=false,\
        config.s3_archive_url="https://minio",config.s3_archive_bucket=lega,config.s3_archive_ca="/ega/tls/root.ca.crt",\
        s3inbox.deploy=true,config.s3_inbox_backend_url="https://minio",config.s3_inbox_backend_bucket=lega,\
        config.s3_inbox_backed_cacert="/etc/ega/ssl/root.ca.crt",podSecurityPolicy.create=false,persistence.enabled=false,\
        tester.run=true,tester.imagePullPolicy=Always
    - name: Wait for e2e test to complete
      run: |
        RETRY_TIMES=0
        until kubectl get jobs localega-e2e-tester -o jsonpath='{.status.conditions[?(@.type=="Complete")].status}' | grep "True" || [ $RETRY_TIMES -eq 30 ] ; do echo "waiting for e2e-test to complete"; RETRY_TIMES=$((RETRY_TIMES+1)); sleep 10; done
        if [ $RETRY_TIMES -eq 30 ]; then exit 1; fi
    - name: show pods
      run: kubectl get pods
